### ISSUE TITLE
pp3 / signs to big

### ISSUE THREAD

**Issue by ghost** [NCC-Lykos/neocron-classic#105]
- [ ] this signs are to big see screenshots it is in pp3 in the genrep room
![shot0003](https://user-images.githubusercontent.com/32795552/32179831-aea70fd6-bd90-11e7-858e-99676d653b16.png)
![shot0004](https://user-images.githubusercontent.com/32795552/32179832-aec9adf2-bd90-11e7-89b4-927e6104898b.png)

**Comment by ghost** [comment]
at the venture warp in pp3 see screens
![shot0000](https://user-images.githubusercontent.com/32795552/32180014-1ec9419e-bd91-11e7-8120-d2bc36f42545.png)
![shot0001](https://user-images.githubusercontent.com/32795552/32180015-1ee4a27c-bd91-11e7-9183-6531fa22142f.png)

**Comment by ghost** [comment]
pp3 at the snack bar
![shot0000](https://user-images.githubusercontent.com/32795552/32180227-aaf8437c-bd91-11e7-9ba5-6eb9fbc40ea8.png)

**Comment by ghost** [comment]
yakarma store in pp3.. move it in the middle .... ![shot0000](https://user-images.githubusercontent.com/32795552/32180376-13bbc690-bd92-11e7-86cb-b5a0a5f171cb.png)
![shot0001](https://user-images.githubusercontent.com/32795552/32180378-13dd5eae-bd92-11e7-86aa-d14b90ba353d.png)

**Comment by ghost** [comment]
most all of this signs in the game to big / out of position make them all smaller?!?! like this one here looks good ! see screen 
![shot0002](https://user-images.githubusercontent.com/32795552/32180440-49cd968c-bd92-11e7-9acf-44f7f4fc007c.png)

**Comment by NCC-Lykos** [comment]
So, we will correct some positioning but here are some things to note...

1. Some of that is a 3D holographic effect type deal. It will pop away from the background and bleed over the edges a bit. Think of a projector...      [Back] < Image     It projects out from a cone < and will sometimes be larger than what it is being projected out of...
2. The sign backs cannot be resized easily. Their dimensions are static, however we can make them larger and smaller overall. It is what it is, and right now not a priority.

Zones over time will be freshened up and new backs installed etc. but for now we are focused on what is causing the game to break and not function...not so much on looks.

With that being said, I'm going to go ahead and close this one for now.
