### ISSUE TITLE
Flying or wrong placed Objects

### ISSUE THREAD

**Issue by Skansy** [NCC-Lykos/neocron-classic#11]
Here is a small list of flying or wrong placed Objects i found.

## Jeriko (B 08)
- [x] Small bush on the right side behind the OP Building ![20171015162313_1](https://user-images.githubusercontent.com/32749567/31585773-c7c397c0-b1c7-11e7-9ec5-15193527b0d7.jpg)

- [x] Advertise Glowboard inside the Shop ![20171015162427_1](https://user-images.githubusercontent.com/32749567/31585785-029ea484-b1c8-11e7-818b-44fb04ceb8e0.jpg)

- [x] Small Tree inside OP ![20171015162544_1](https://user-images.githubusercontent.com/32749567/31585801-30cfdefe-b1c8-11e7-9aac-3e566147a1dd.jpg)

- [x] Outpost Trader Building is flying :) ![20171015162502_1](https://user-images.githubusercontent.com/32749567/31585810-4c5223da-b1c8-11e7-8e16-be86a49469a2.jpg)

**Comment by ghost** [comment]
I've fixed two of the issues that were brought up in here.

**Comment by NCC-Lykos** [comment]
@Skansy I believe I have fixed the trader shop. 
![screen shot 2019-01-07 at 9 38 03 pm](https://user-images.githubusercontent.com/24256285/50808551-af924700-12c4-11e9-85e0-3bf68ceb52fe.png)

**Comment by Skansy** [comment]
> @Skansy I believe I have fixed the trader shop.
> ![screen shot 2019-01-07 at 9 38 03 pm](https://user-images.githubusercontent.com/24256285/50808551-af924700-12c4-11e9-85e0-3bf68ceb52fe.png)

looks much better ... thanks :)

**Comment by NCC-Lykos** [comment]
Fixed for next patch
