### ISSUE TITLE
neocron 2 music still playing

### ISSUE THREAD

**Issue by ghost** [NCC-Lykos/neocron-classic#110]
in many sectors like headquarters / techhaven / militarybase / are playing music from neocron 2 ! 
in neocron 1 this areas got the normal music and not this annoying tracks can you change it ?

you can find in the game direction  \Neocron Classic\clients\retail\sound\mp3, 3-folders named CLUBMUSIC 1-3 that are music from the neocron 2 client delete them^^

**Comment by NCC-Lykos** [comment]
I'm going to leave this as player preference. It is not a bug.

**Comment by ghost** [comment]
@NCC-Lykos  player preference ?? haha i think you guys want to rebuild neocron 1(1) ???? and this shitty music tracks from neocron 2 ( 2 ) client only bring player to turn off ingame music.. example: go to military base and listen to this music it is annoying for every player in this sector... if you say you like it then you got no ear for music ... game atmosphare with this background music sucks hard

**Comment by NCC-Lykos** [comment]
The player can remove the track or change the track. They have full control over the music file.

**Comment by ghost** [comment]
I don't mind the music, so I agree that it comes down to a preference and not necessarily a bug.  You can turn the music level down in game, too.
