### ISSUE TITLE
trader in i04 sell wrong stuff

### ISSUE THREAD

**Issue by ghost** [NCC-Lykos/neocron-classic#116]
- [ ] the trader in the outpost i04 (sieger uplink) sell the wrong stuff see screenshot
![shot0000](https://user-images.githubusercontent.com/32795552/35409732-023d6cbc-020b-11e8-8df5-b8723fda29b8.png)

- [ ] the traders outside the outpost at this wooden houses sell wrong stuff too i think they are 5 trader see screenshot for location.
![shot0002](https://user-images.githubusercontent.com/32795552/35409827-4882a048-020b-11e8-96ed-44dd32e39350.png)
![shot0000](https://user-images.githubusercontent.com/32795552/35409919-928a754e-020b-11e8-9f06-3059f365838f.png)

**Comment by ncc-gnisha** [comment]
@hazuk The first screenshot that you've posted with the Yo's Vendor selling "Outpost Equipment", this is as intended.

**Comment by ghost** [comment]
Fixed the outpost vendor.

The other smugglers have been removed while we figure out final trader placement, what they sell, etc.
