### ISSUE TITLE
Aggie Celler Plaza 2 Respawn!!

### ISSUE THREAD

**Issue by Blackeast** [NCC-Lykos/neocron-classic#117]
HI. 
The Aggie Celler Plaza 2 have not the Right respawn Rate atm.

Me and me Frend Leveling on it atm and the Junck are on the Floor after Selling ( 1-2 Min )
And we are the only 2 on it atm 

And the Mobs need 2-5 min to Respawn after killing

**Comment by NCC-Lykos** [comment]
I checked this in game with you just now, confirmed that spawns were back to normal.

This was more than likely an issue with the zone initializing. All good now :)
