### ISSUE TITLE
Team EXP Buggd

### ISSUE THREAD

**Issue by Blackeast** [NCC-Lykos/neocron-classic#126]
I Leveling on a 4 man Team at J 01 ( MB ) like 1-2 hours.
I Have PSI Lev  40 Base, and have only make 15-20 % exp to 41

The Player are
Me PPU 19/29
APU 16/21
APU 15/20
PE     07/22
The EPX its not Normal pls help

**Comment by Blackeast** [comment]
OK We Find the 2 Team Bugg.

After 5-10 min Leveing on a Team the EXP Stop Complet for all in the Team

**Comment by ghost** [comment]
To comment on this; MayhemMike and myself did a quick little test with this.

We both can be killing mobs, and we see the money being split between the two runners; however we're not sharing _any_ XP in any skills.

**Comment by NCC-Lykos** [comment]
So update on this, Therenall is looking into it but we don't know if this is caused by Neocrons absolutely back woods way of calculating XP, or if it is a bug introduced with Storage.

**Comment by NCC-Therenall** [comment]
Just as a heads up, I've got something that should fix this that should be coming soon. I just got distracted messing with other XP related stuff yesterday, lol. I'll try to push some changes up for patching today.

**Comment by NCC-Therenall** [comment]
So to clarify what exactly happened: skills have a level-based cap to how much. This translates roughly to "How much XP can I get per hit". I believe this cap was not being updated on level, causing players (everyone I've looked at so far) to be getting starting-level XP gain caps per hit. 

Once this fix is up, I believe it should resolve the team XP bug, as well as XP being smoother in general.

**Comment by NCC-Therenall** [comment]
I'd like some input on XP now before closing this.

**Comment by Blackeast** [comment]
The XP it's much better. The Problem with the Team still. ( when anyone Relog or has Fatal )
I think the Team are the Probelm not the XP at this Point ( I ppu bsw )

If you need a new Report for this i make one and you can Close this.

**Comment by NCC-Therenall** [comment]
There's an issue for the other team bugs (You made it actually.) So I'll go ahead and close this one. Thanks!
