### ISSUE TITLE
bug on loms

### ISSUE THREAD

**Issue by M-ace** [NCC-Lykos/neocron-classic#127]
took a wep lore lom and crashed me. logged back in, took another and everything was fine.  same thing happend to gnisha so makin a post

**Comment by ghost** [comment]
To add to this, when the client initially crashed on me it was just a hard crash to desktop. No log entries, etc.

**Comment by M-ace** [comment]
same

**Comment by ghost** [comment]
This issue was fixed some time ago.  Just double checked that LoM's do work without crashing.
