### ISSUE TITLE
cyberhound citycom mission

### ISSUE THREAD

**Issue by M-ace** [NCC-Lykos/neocron-classic#128]
the cyberhound missions found in citycom seem to be out of place.  cyberhounds are 10/10,  their smaller brother, the houndbot 8/8 is listed as a normal mission, while the cyberhound 2 ranks higher is listed as easy.  so killing the higher mob results in less mission xp and reward

**Comment by ghost** [comment]
There are a lot of terminal missions I need to dig into.

**Comment by ghost** [comment]
This has been fixed.

The CYBERHOUND 10/10 and HOUNDBOT 8/8 are both in the "easy" difficulty. There was also a duplicate mission for the HOUNDBOT under the "normal" difficulty. The "normal" difficulty mission has been removed.  

Watch the patch notes for this fix when its patched in.

**Comment by M-ace** [comment]
Shouldnt cyberhound be in normal? Based off the other stuff around the same
level. Like mech turtles and big mech turtles  both are normal iirc. Sorry
on cell working now else i would check.

**Comment by ghost** [comment]
Nah, both missions have a difficultly rating of 11, thus both fall under the "easy" category.
