### ISSUE TITLE
yo's mb

### ISSUE THREAD

**Issue by M-ace** [NCC-Lykos/neocron-classic#129]
are the yo's at mb center not supposed to be all buyers?  cuz they dont buy anything that ive gotten as drops from mobs so far.  so ive littered the storage areas with useless stuff that i cant use for recycling.  would be a great way to make money selling the imps that launchers drop.

**Comment by ghost** [comment]
@M-ace While I'm working on this, you can sell the implants that you get from the mobs at Crytons inside the Military Base.  I'm working on getting these vendors to buy all your junk.

**Comment by M-ace** [comment]
Ok cool. Just my junk tho lol. Let others suffer like i did lol

**Comment by ghost** [comment]
Fixed.
