### ISSUE TITLE
Gatling Pistol and PE Model Bug

### ISSUE THREAD

**Issue by therealsf** [NCC-Lykos/neocron-classic#136]
My PE Pacer was using the level 56ish gatling pistol last night and it is not carried on the side of the hips like the other pistols, but on the chest....looks odd ;)

**Comment by Skansy** [comment]
Gatling Pistol / Rifle / Cannon are all on the Back, cause they are so big and heavy :)
its always like that and on purpose

**Comment by therealsf** [comment]
ye, the Gatling Pistol is however on the chest. like a middle boob pointing to the front ;)

**Comment by Skansy** [comment]
ohhhhhh maybe you could add a screenshot to show the bug :)

**Comment by therealsf** [comment]
good idea...haha
![ncbug](https://user-images.githubusercontent.com/36111792/35866685-1f7a4dd0-0b58-11e8-9f26-9501b1b3ff22.png)

**Comment by ghost** [comment]
With the return of the Neocron 1 models this is no longer an issue.  Closing this for now.

**Comment by rhomm-dev** [comment]
> 
> 
> With the return of the Neocron 1 models this is no longer an issue. Closing this for now.

It's still in with at least PE power armor:

![ncc_gatling_pistol](https://user-images.githubusercontent.com/34965105/49622837-1e644380-f999-11e8-90a9-e43308d349bd.png)

and possibly related, freezer rifle:

![ncc_thunderbolt_freeze_rifle](https://user-images.githubusercontent.com/34965105/49622851-2e7c2300-f999-11e8-8df3-b3346f01ef64.png)

**Comment by ghost** [comment]
I've reopened this issue.

**Comment by ghost** [comment]
@NCC-Camarogue

**Comment by NCC-Lykos** [comment]
These should all be fixed, we've also quit using the "New" models.
