### ISSUE TITLE
Fatals, Syncs

### ISSUE THREAD

**Issue by therealsf** [NCC-Lykos/neocron-classic#138]
I am having fatals and sync errors very frequently.
different kind of crashes:

1. client crashes to desktop, windows prompting me that neocron has stopped working
2. avatar is in the sync screen and i can rotate it when moving mouse - endless sync - need to relog the character > after relog my avatar seems to be a default model which would not change until i sync again

Syncing errors are highly probable after a certain amount of time (my feeling is around 15-30 minutes) has passed.

My PC Spec: (neocron however doesnt let me utilize the geforce and iam forced to play with the intel gfx - which means I am having permanently low fps when in outdoor zones)

Betriebsystemname	Microsoft Windows 10 Home
Version	10.0.16299 Build 16299
Weitere Betriebsystembeschreibung 	Nicht verfügbar
Betriebsystemhersteller	Microsoft Corporation
Systemname	LAPTOP
Systemhersteller	ASUSTeK COMPUTER INC.
Systemmodell	K501UW
Systemtyp	x64-basierter PC
System-SKU	ASUS-NotebookSKU
Prozessor	Intel(R) Core(TM) i7-6500U CPU @ 2.50GHz, 2592 MHz, 2 Kern(e), 4 logische(r) Prozessor(en)
BIOS-Version/-Datum	American Megatrends Inc. K501UW.301, 13.09.2016
SMBIOS-Version	3.0
Version des eingebetteten Controllers	255.255
BIOS-Modus	UEFI
Hauptplatinenhersteller	ASUSTeK COMPUTER INC.
Hauptplatinenmodell	Nicht verfügbar
Hauptplatinenname	Hauptplatine
Plattformrolle	Mobil
Sicherer Startzustand	Aus
PCR7-Konfiguration	Erweiterung zum Anzeigen erforderlich
Windows-Verzeichnis	C:\WINDOWS
Systemverzeichnis	C:\WINDOWS\system32
Startgerät	\Device\HarddiskVolume2
Gebietsschema	Deutschland
Hardwareabstraktionsebene	Version = "10.0.16299.192"
Benutzername	LAPTOP\xxxxx
Zeitzone	Mitteleuropäische Zeit
Installierter physischer Speicher (RAM)	8,00 GB
Gesamter physischer Speicher	7,86 GB
Verfügbarer physischer Speicher	3,50 GB
Gesamter virtueller Speicher	9,11 GB
Verfügbarer virtueller Speicher	3,52 GB
Größe der Auslagerungsdatei	1,25 GB
Auslagerungsdatei	C:\pagefile.sys
Unterstützung der Geräteverschlüsselung	Erweiterung zum Anzeigen erforderlich
Hyper-V - VM-Monitormoduserweiterungen	Ja
Hyper-V - SLAT-Erweiterungen (Second Level Address Translation)	Ja
Hyper-V - Virtualisierung in Firmware aktiviert	Ja
Hyper-V - Datenausführungsverhinderung	Ja

Name	Intel(R) HD Graphics 520
PNP-Gerätekennung	PCI\VEN_8086&DEV_1916&SUBSYS_11E01043&REV_07\3&11583659&1&10
Adaptertyp	Intel(R) HD Graphics Family, Intel Corporation-kompatibel
Adapterbeschreibung	Intel(R) HD Graphics 520
Adapter-RAM	1,00 GB (1.073.741.824 Bytes)
Installierte Treiber	C:\WINDOWS\System32\DriverStore\FileRepository\igdlh64.inf_amd64_463164d40c3d26ce\igdumdim64.dll,C:\WINDOWS\System32\DriverStore\FileRepository\igdlh64.inf_amd64_463164d40c3d26ce\igd10iumd64.dll,C:\WINDOWS\System32\DriverStore\FileRepository\igdlh64.inf_amd64_463164d40c3d26ce\igd10iumd64.dll,C:\WINDOWS\System32\DriverStore\FileRepository\igdlh64.inf_amd64_463164d40c3d26ce\igd12umd64.dll
Treiberversion	21.20.16.4550
INF-Datei	oem28.inf (Abschnitt iSKLD_w10_DS)
Farbebenen	Nicht verfügbar
Farbtabelleneinträge	4294967296
Auflösung	1920 x 1080 x 59 Hz
Bits/Pixel	32
Speicheradresse	0xDD000000-0xDDFFFFFF
Speicheradresse	0xB0000000-0xBFFFFFFF
E/A-Port	0x0000F000-0x0000F03F
IRQ-Kanal	IRQ 4294967287
E/A-Port	0x000003B0-0x000003BB
E/A-Port	0x000003C0-0x000003DF
Speicheradresse	0xA0000-0xBFFFF
Treiber	c:\windows\system32\driverstore\filerepository\igdlh64.inf_amd64_463164d40c3d26ce\igdkmd64.sys (21.20.16.4550, 10,53 MB (11.039.712 Bytes), 30.11.2016 07:33)
	
Name	NVIDIA GeForce GTX 960M
PNP-Gerätekennung	PCI\VEN_10DE&DEV_139B&SUBSYS_11E01043&REV_A2\4&109ADFC2&0&00E0
Adaptertyp	GeForce GTX 960M, NVIDIA-kompatibel
Adapterbeschreibung	NVIDIA GeForce GTX 960M
Adapter-RAM	(2.147.483.648) Bytes
Installierte Treiber	C:\WINDOWS\System32\DriverStore\FileRepository\nvami.inf_amd64_40aceccb38b252dc\nvldumdx.dll,C:\WINDOWS\System32\DriverStore\FileRepository\nvami.inf_amd64_40aceccb38b252dc\nvldumdx.dll,C:\WINDOWS\System32\DriverStore\FileRepository\nvami.inf_amd64_40aceccb38b252dc\nvldumdx.dll,C:\WINDOWS\System32\DriverStore\FileRepository\nvami.inf_amd64_40aceccb38b252dc\nvldumdx.dll
Treiberversion	23.21.13.8871
INF-Datei	oem78.inf (Abschnitt Section140)
Farbebenen	Nicht verfügbar
Farbtabelleneinträge	4294967296
Auflösung	1920 x 1080 x 60 Hz
Bits/Pixel	32
Speicheradresse	0xDE000000-0xDEFFFFFF
Speicheradresse	0xC0000000-0xCFFFFFFF
Speicheradresse	0xD0000000-0xD1FFFFFF
IRQ-Kanal	IRQ 4294967288
Treiber	c:\windows\system32\driverstore\filerepository\nvami.inf_amd64_40aceccb38b252dc\nvlddmkm.sys (23.21.13.8871, 16,24 MB (17.028.552 Bytes), 02.01.2018 21:31)

**Comment by M-ace** [comment]
as far as i know, nc has never utilized ur graphics card.  unless they made changes to this version (which would be awesome)  i would think that would be coming when nc goes to the 64 bit version later down the line.  devs, fill us in lol

**Comment by NCC-Lykos** [comment]
So, NC has always utilized the graphics card....I mean, that is kinda how it works? Also, this is months old and we cannot reproduce.

**Comment by NCC-Lykos** [comment]
This is months old and we cannot reproduce it.
