### ISSUE TITLE
Tanget Epic Mision 5 and 6

### ISSUE THREAD

**Issue by tuxhomer** [NCC-Lykos/neocron-classic#140]
Tux - heute um 21:27 Uhr
hi. i have 2 problems, but is one. for the tt epic i must kill an biotech employ in via 1 at the 5. mission. at missin 6 i have to kill the biotech director in via 1 too
but via 1 is a save zone ^^
Atlas - heute um 21:28 Uhr
did you check inside the building? I could have sworn we moved him inside
there might be duplicate files at play
Tux - heute um 21:29 Uhr
and the biotech employee?
via 1 is a savezone
Atlas - heute um 21:30 Uhr
was the director inside? I need to know so I can figure out if there is a wrong file on the live server
Tux - heute um 21:31 Uhr
yes
Atlas - heute um 21:31 Uhr
oh boy, okay lemme talk to someone that might be at home
Gnisha - heute um 21:32 Uhr
There are still a handful of duplicate npcs around that haven't been cleared outm
Atlas - heute um 21:32 Uhr
naw that was fixed a while ago, there's definitely some fucky files
Gnisha - heute um 21:32 Uhr
There should also be biotech employees inside bt hq
Tux - heute um 21:32 Uhr
and please fix the savezone problem :smiley:
Gnisha - heute um 21:32 Uhr
Even on my local dev env there are duplicate npcs
Bt director one of them
Atlas - heute um 21:33 Uhr
yes... er, anyway Tux
that's up for debate, we still gotta balance and see which ones remain safe and which dont lol
Tux - heute um 21:33 Uhr

^^
Esc zum Abbrechen • Enter zum Speichern
NEUE NACHRICHTEN
Gnisha - heute um 21:34 Uhr
I'll look at it tonight after work though.
Submit a bug report so I don't forget though

**Comment by tuxhomer** [comment]
Update:
I killed some employees in the BT HQ for the 5. Mission. 
They didn't work for the Mission

**Comment by tuxhomer** [comment]
Update2:
I have finished the 5. Mission.
The part with kill one Biotech employee was not part of the mission, or the kills are not shown in the chat window.
The solutions for the 6. mission are:
1. Move the Biotech Director, seated inside the restaurant in Via 1, to the BT HQ
or
2. Make Via 1 to a PVE Zone

**Comment by tuxhomer** [comment]
I have an idea for the Biotech Director for the 6. Mission.
Place the Director in one of the Ceres Labs and call it Secret Weapon Facility or something else.
The info there the Facility is gives you  Andressa.

**Comment by ghost** [comment]
Why would we place a Faction Director in an out of the way spot in the wastelands? Also we don't have Ceres Labs on our servers.

**Comment by ghost** [comment]
@tuxhomer I just double checked the BioTech HQ and the Director of Operations is seated at his desk inside the HQ.

I'll be talking with the team on which one of these NPCs we want to keep.

**Comment by tuxhomer** [comment]
Update:
The Epic works now, but you didn't get infos for the kills in the chat window.
The BT Epic have the same problem

**Comment by ghost** [comment]
Closing this issue for now as the Directors have been properly placed and zone security is now correct on those zones.

The issue regarding the kill count in the chat window not always being displayed is taken care of inside of another issue.
