### ISSUE TITLE
Negative Soullight loss after death

### ISSUE THREAD

**Issue by NCC-Atlas** [NCC-Lykos/neocron-classic#142]
User was leveling in aggie sewers and Pepper Park sector 3 sewers. After a respawn, had negative soullight at about -37.

**Comment by NCKryptonite** [comment]
In aggie sewers, it's labeled as a PVE zone, but you can still dmg/kill other players. That might be how it happened if someone died before you/they left & weren't teamed.

**Comment by NCC-Therenall** [comment]
@NCC-Lykos / @NCC-Atlas is this still an issue, or can I close this?
