### ISSUE TITLE
NPC Based Mission Descriptions Not Working

### ISSUE THREAD

**Issue by ghost** [NCC-Lykos/neocron-classic#144]
![missiontexterror](https://user-images.githubusercontent.com/32779211/35782222-9040264c-09ba-11e8-8feb-f373491232d4.png)

As seen in the attached screenshot, NPC based mission dialogs are not displaying the correct text associated with the mission.

**Comment by tuxhomer** [comment]
Sometimes a relog helps to show the mission text.

**Comment by NCC-Gnisha** [comment]
> Sometimes a relog helps to show the mission text.
So far, for me, multiple relogs do not fix the problem.

**Comment by ghost** [comment]
Adding some information.

This does not happen on _all_ of the missions with text dialogs.  For example, CityAdmin Epic Mission 1 works fine.

**Comment by NCC-Lykos** [comment]
Fixed.
