### ISSUE TITLE
LE Char can DMG LA Char

### ISSUE THREAD

**Issue by Blackeast** [NCC-Lykos/neocron-classic#146]
my LE Char can DMG a ather LE Char but not healing

Testet on Arpartment Sec.

**Comment by M-ace** [comment]
yea, i noticed yesterday all the sudden i cant heal my spy with my tank.  im sure i could a couple days ago

**Comment by NCC-Lykos** [comment]
- [ ] LE Runners can damage and kill each other
- [ ] LE Runners cannot heal or resurrect each other
