### ISSUE TITLE
Runner without LE apears to be using LE in the "closeby character window"

### ISSUE THREAD

**Issue by therealsf** [NCC-Lykos/neocron-classic#148]
![ncbug1](https://user-images.githubusercontent.com/36111792/35882168-89b40486-0b83-11e8-9cb8-6d20d55bca39.png)

**Comment by ghost** [comment]
Did the runner just remove their LE? Re-zone?

**Comment by therealsf** [comment]
I did not ask him. The last time i saw him (yesterday or the day before..) he was yellow as in without LE. 

I did not try to attack him, since plaza 1 is heavily guarded.

**Comment by NCC-Lykos** [comment]
If it is a pve zone all will appear to have an LE as the pve zone disables PvP.

**Comment by NCC-Lykos** [comment]
Plaza one is a pve zone currently. Closing this as functions as normal for now.
