### ISSUE TITLE
Invisible walls blocking vendors in Twilight Canyon trading post

### ISSUE THREAD

**Issue by Ruojanaama** [NCC-Lykos/neocron-classic#152]
Two of the vendors are completely inaccessible in the trading post by invisible walls

**Comment by ghost** [comment]
Can you please provide a screenshot of the vendors with your minimap open?

**Comment by Ruojanaama** [comment]
![nimetontg](https://user-images.githubusercontent.com/36326913/36070867-db81977e-0f0c-11e8-8c3e-5e8425414c73.jpg)

there you go

**Comment by ghost** [comment]
Thanks.  Will check this out.

**Comment by ghost** [comment]
Fixed.
