### ISSUE TITLE
Characters stuck in Appartement, Client crashes on Login

### ISSUE THREAD

**Issue by RorixBladewing** [NCC-Lykos/neocron-classic#154]
Got an Issue for an hour now where my chars stuck in an Appartement (Verizon Arcade Enter B // Negan)
Right after the "tutorial messages" are popping up the game freezes, the client crashes and all login tries to an character stuck in this Appartement resolving in "Client not working anymore".

Filecheck did nothing, all other chars outside are working well.

**Comment by RorixBladewing** [comment]
Small Update, i "fixed" it, seems to be an issue with the german language tutorial messages, switching to english did it.

**Comment by ghost** [comment]
@RorixBladewing when the server is back online can you verify if this is still an issue? I haven't been able to reproduce this.

**Comment by ghost** [comment]
Being unable to duplicate this issue and not hearing anything back from @RorixBladewing, I am closing this issue.
