### ISSUE TITLE
Cannot Use Plasma Pistol in E11

### ISSUE THREAD

**Issue by therealsf** [NCC-Lykos/neocron-classic#157]
game doesnt let me pull out my weapon (plasma pistol) in E 11 - i can however take out dmg boost (slot 5) and the lowtec pistol (slot 4).

it works in the other zones.
![sdgsdfsf](https://user-images.githubusercontent.com/36111792/36067517-ca85d24e-0ebe-11e8-8dc4-6c005f5e5f42.jpg)

**Comment by ghost** [comment]
This could also be a problem with drugs and/or boosters.  While it says "You cannot use this item, yet" what are your stats and skills saying you're at?

**Comment by therealsf** [comment]
i was not using drugs. apart from stamina boosters. 
i had no synaptic imparement.

when syncing to the zone north of E11 i could immediatly use slot 1. after syncing back to E11 the problem still occured

**Comment by therealsf** [comment]
same issue in I11

**Comment by Stevil79** [comment]
Can't use any weapons in F12 (CRP) or B6 either.

If you GR out and back in again the bug fixes itself at CRP. Not sure if the other affected zones have GRs in them to fix though. B6 does but I don't think E11 or I 11 have.

Maybe an issue to do with syncing at zone lines?
