### ISSUE TITLE
Raptor do poison Stack Damange

### ISSUE THREAD

**Issue by Skansy** [NCC-Lykos/neocron-classic#158]
The Raptor is shooting his Fireball but will give you a Poison Stack.
![raptor-do-poison](https://user-images.githubusercontent.com/32749567/36074337-2ee3259a-0f3f-11e8-8506-66ba982916a4.jpg)

**Comment by RorixBladewing** [comment]
Edit, every Firemob deals massive Poison Damage atm

**Comment by NCC-Lykos** [comment]
Fantastic job Neocron! Just another fun little "Fix one thing, break 20 more" Bug.

I'll fix this shortly.

**Comment by M-ace** [comment]
so in the meantime we wear poison gear against fire mobs?  anyone know if poison mobs do fire damage?
