### ISSUE TITLE
Plaza 1 Snackbar goes crazy xD

### ISSUE THREAD

**Issue by Skansy** [NCC-Lykos/neocron-classic#159]
I think something went wrong :)

![xd](https://user-images.githubusercontent.com/32749567/36076438-55d423e4-0f5c-11e8-9705-b4dbc3b8d47a.jpg)

**Comment by NCC-Lykos** [comment]
There was a ripple in time and space. It will be fixed shortly.

**Comment by NCC-Atlas** [comment]
I'm a bit miffed by this, the first time players see the updated City Admin approach and it looks totally screwed up.

**Comment by ghost** [comment]
there still some benches left to delete! see screenshots. is there no way to fly with noclip outside map and watch from a better view to check what you patch?
![shot0000](https://user-images.githubusercontent.com/32795552/36442426-097b3c82-1676-11e8-8452-587df477c14f.png)
![shot0001](https://user-images.githubusercontent.com/32795552/36442428-099d40e8-1676-11e8-8a1c-1af23def243f.png)

**Comment by ghost** [comment]
Adding a keyword for searching previous bug reports:  fountain

**Comment by ghost** [comment]
This has been fixed a few patches ago.
