### ISSUE TITLE
Epics - CityAdmin */40

### ISSUE THREAD

**Issue by NCC-Atlas** [NCC-Lykos/neocron-classic#165]
The kill targets for the CityAdmin epic questline are not functional. Ethan Cole requests that a Runner kills three Twilight Guardian contact persons located in Pepper Park 3. None of the kills register.

**Comment by throche** [comment]
I did the CA epics yesterday night, I killed the 3 TG contact persons standing at near the stairs in PP3. it worked fine. The chat didn't mention the kills registered but the mission went on smoothly.

**Comment by NCC-Atlas** [comment]
So the most prudent course of action is to find out why for some players they don't register, also why the text prompt doesn't show up.
