### ISSUE TITLE
Jeriko OP - Logging out

### ISSUE THREAD

**Issue by Stevil79** [NCC-Lykos/neocron-classic#171]
I've logged out twice in the Jeriko OP and both times when I come back in my character had penalties on Pistol Combat and Tech Combat causing me to be unable to use my weapon. This bug is repeatable.

The bug fixes itself after you log out for a period of time in another zone.

**Comment by M-ace** [comment]
i wonder if this happens in all or more fortress zones

**Comment by ghost** [comment]
I wonder if this is related to Issue #157

**Comment by Stevil79** [comment]
I've had the 157 bug as well at Point Red. I checked my skill points and they were unaffected. It just said I couldn't use the weapon in slot 1 due to requirements or something.

**Comment by Stevil79** [comment]
Also confirmed that if you crash within the zone and log straight back in the negative effects occur.

**Comment by NCC-Therenall** [comment]
Closing to consolidate into #297
