### ISSUE TITLE
Can't launch game

### ISSUE THREAD

**Issue by butterrmahjely** [NCC-Lykos/neocron-classic#174]
Just did a reformat to my computer. 

Here's the list of updates I've already done to my computer since reformat:
-All Windows updates
-Nvidia Graphic Drivers
-C++ Redistribution
-Microsoft Framework NET

Running as Admin and updating the launcher and hitting Play, I get the error shown in the screenshot.
![89365ae4-28aa-4a8c-9547-a051b964e1eb](https://user-images.githubusercontent.com/6628124/36406174-e942e112-15c2-11e8-971b-4325d6fb102c.jpg)

I'm using a GTX 1070 @ 2560x1440p.

Mind you the game was running just fine before the reformat.

Thanks.

**Comment by ghost** [comment]
That error is typically associated with the game not able to find a compatible video card/driver to launch with.

What version of Windows are you running? DirectX 9 installed? 

Also make sure you have both 32-bit and 64-bit Visual Studio 2015 runtimes installed.

**Comment by butterrmahjely** [comment]
Hi Gnisha,

See screenshot. I have both x64 and x86 VC Redistribution Runtimes installed.

![image](https://user-images.githubusercontent.com/6628124/36435273-396e80a8-162f-11e8-8b15-2c16502fdd7c.png)

Error is still persisting.

**Comment by butterrmahjely** [comment]
Solved the issue.

Needed to install older redistribution files (Runtimes from 2005-2015) and installed older direct x files.

You can close.
