### ISSUE TITLE
Client Crash After Minimise

### ISSUE THREAD

**Issue by SoulNC** [NCC-Lykos/neocron-classic#175]
Client is crashing every time I minimise since the latest patch update. Wasn't an issue previously and tested multiple times to wish to crashes every time.

**Comment by hinch** [comment]
+1 for me too

**Comment by Stevil79** [comment]
And me.

**Comment by butterrmahjely** [comment]
happened to me after alt+tabbing out of the game

**Comment by throche** [comment]
I'd add that I've always crashed when alt-tabbing while in the wasteland but never while in NC city districts.

**Comment by ColeMcNamara** [comment]
Same Here. Crash everytime i Alt-Tab without Window mode or minimize with Window-Mode ( happens in every Zone i tryd : NC; MB; j01,J02; TH)

**Comment by NCC-Lykos** [comment]
This has been fixed for next patch.
