### ISSUE TITLE
Birds in tutorial a little spazzy

### ISSUE THREAD

**Issue by hinch** [NCC-Lykos/neocron-classic#176]
Its nice to see birds flying again but can birds also please fly in the sky not just in the floor.

I would attach a screenshot but alt/tabbing out the tutorial to save it into this report caused NC to crash and flush the C&P buffer :(

**Comment by NCC-Atlas** [comment]
Tutorial has many more issues than that. A few of our item organization updates broke a few of the steps.

This is indeed a reminder that the tutorial needs some love, though.

**Comment by hinch** [comment]
yeah there's also an interesting one tied with the current alt + tab crash bug.  when in tutorial if you alt tab and crash the client when you log back in you don't resume the tutorial but then start in your apartment with no other explanation of what is going on and none of the benefits of completing the tutorial :)

**Comment by NCC-Lykos** [comment]
The tutorial will get love someday. Closed as not current bug.
