### ISSUE TITLE
Outpost Bonus Bug

### ISSUE THREAD

**Issue by Skansy** [NCC-Lykos/neocron-classic#177]
I dont know if its because the outpost belong to noone but when i sync out of a Outpost, the Bonus convert into a Malus.

When this malus decrease ur skills so u cant use your vehicle, that you are currently driving, you will stuck in sync.

**With Vehicle:**
- I Synct into Devereaux Fortress on my Vehicle
- i Synct out of Devereaux Fortress on my Vehicle and Stuck in Sync
- I log back in and cant use my Vehicle
- I wait until my character despawn to log back in and everything is fine

**Without Vehicle:**
- I Synct into Devereaux Fortress without my Vehicle
- i Synct out of Devereaux Fortress without my Vehicle
- i cant use my Vehicle
- I wait until my character despawn to log back in and everything is fine

**Comment by cptYokom** [comment]
This also happens at other outpost. I was in a Gabanium mine outpost and my recycle skill had a -50 factor. I had 21 in my recycle skill and it showed -21. I put the tradeskill glove on and the bonus applied was only 150 not the 200 rated on the glove so my total recycle was 171. Yes this means you cant recycle for ammo from junk in a mine outpost

This also applies to the outpost underground.

**Comment by NCC-Therenall** [comment]
Closing this to consolidate into one issue: #297
