### ISSUE TITLE
Hack Interface dont show "needed hackpoints"

### ISSUE THREAD

**Issue by Skansy** [NCC-Lykos/neocron-classic#178]
When i do hacking, the Window doesnt tell me how many "Stars" i need.

This is what it looks like for me:
![20180221021215_1](https://user-images.githubusercontent.com/32749567/36458113-86caf84e-16ad-11e8-8a59-cbef744c5b82.jpg)

This is what i know from Neocron normaly:
![20180221021554_1](https://user-images.githubusercontent.com/32749567/36458149-aef45054-16ad-11e8-89ca-2591a35b9c3a.jpg)

Is it a bug or just changed?

**Comment by NCC-Lykos** [comment]
This has been fixed for next patch.
