### ISSUE TITLE
Graphical Glitches at Edges (2560x1080 Windowed)

### ISSUE THREAD

**Issue by Stevil79** [NCC-Lykos/neocron-classic#180]
![20180221190015_1](https://user-images.githubusercontent.com/36552639/36499693-fdf548a2-1739-11e8-8135-66d228d90064.jpg)
![20180221190053_1](https://user-images.githubusercontent.com/36552639/36499694-fe11e52a-1739-11e8-92f1-c5061714a934.jpg)
![20180221190006_1](https://user-images.githubusercontent.com/36552639/36499695-fe31c75a-1739-11e8-8c2d-1bcb7ea511ef.jpg)

Graphics disappear at the top of the screen and to the right. I've tried to show that in my pictures.

Also seems really dark compared to full screen. This issue may be local to me though as I've had some gamma problems which I've fixed, but they persist in windowed mode. Full Screen looks great now though but has the alt-tabbing issue.

**Comment by NCC-Lykos** [comment]
This should be fixed now with next patch.
