### ISSUE TITLE
Texture looks out of place in p3

### ISSUE THREAD

**Issue by hinch** [NCC-Lykos/neocron-classic#181]
Looks like a low res texture has snuck in near the highres ones or its the wrong texture. 
it just looks out of place  see the blurry horrible red/blue crap at the bottom its that whole texture it just looks wrong.

![neocron screenshot 2018 02 21 - 21 39 09 07](https://user-images.githubusercontent.com/2182589/36508173-d81ed6ba-1753-11e8-9f81-45bab6359a93.png)

**Comment by ghost** [comment]
Ah, okay, I see it now.  Took me a minute to spot it.

The first thing I noticed was the wall to the right of center screen; you can see where one texture ends and the other begins.  Two texture bugs in one screenshot; nice catch. :+1:

**Comment by hinch** [comment]
there's those wall joins all over the place just go look at the floor between p1 and p2  at the zone line :) i've been ignoring those as I figured it was just scaling issues with the new textures and they'd get worked out eventually.

**Comment by NCC-Atlas** [comment]
That's bad texture use. That specific texture is more for trimming in very specific purposes not a big wall. I'll change it.

**Comment by NCC-Atlas** [comment]
Fixed (internally, will patch at a later date).

**Comment by hinch** [comment]
you could probably close this now the texture has at least been replaced with a high res one although still used as a whole now its high res it isn't as jarring as before so looks acceptable.
