### ISSUE TITLE
NEXT Epic

### ISSUE THREAD

**Issue by cptYokom** [NCC-Lykos/neocron-classic#186]
You get to the last part and after talking with the TH Elias and killing the Malfunctioning Warbot. You are suppose to go to CA HQ and talk with the "Right" City Admin Employee. This person can not be found. I talked with every employee in the HQ. Went to NCPD in via 3, looked in pepper park where the city admin employees are dancing with hookers. 

Cant be found. Tried 5 times.

**Comment by cptYokom** [comment]
Looking at this again .... The mission window still says.

Erased Memory
A way was found to thwart the plans of ProtoPharm to take over Next with the help of the fallen Angel member Elias. He already waits in Tech Haven. 

So even though you kill the warbot and talk to Elias and go back and talk to him again it isn't moving the mission to the next step and never selecting the city admin employee. So the problem may be with the lua file not moving to the next step once the warbot is killed.

**Comment by cptYokom** [comment]
And yes just after I wrote that was headed to the GR in pepper 3 and boom the city admin employee Strafe Mcdonagh in pepper 2 the one next to the hooker up the grave lift was the mission guy. The 6th time I tried the mission.

**Comment by ghost** [comment]
The mission window text not updating and the proper mission npcs not being picked up is a bug in the mission system that @therenall is working on getting fixed. The actual files that hold the mission text, etc are fine.

**Comment by ghost** [comment]
Adding some additional information and observations from when I just ran this:

:heavy_check_mark:  Mission 1: NPC Pointers and Mission Dialog Window works.

:stop_sign: Mission 2: NO NPC Pointers or Mission Dialog Window text.
* You can still follow the mission instructions and complete the mission.

:stop_sign: Mission 3: NO NPC Pointers or Mission Dialog Window text.
* You can still follow the mission instructions and complete the mission.

:stop_sign: Mission 4: NO NPC Pointers or Mission Dialog Window text.
* You can still follow the mission instructions and complete the mission.
* The BioTech Employee in Via Rosso SEC-1 _should_ have a NPC Pointer to it, but it isn't working. So, you have to go and talk to every BioTech Employee in the sector until you get the mission dialog.

:stop_sign: Mission 5: NO NPC Pointers or Mission Dialog Window text.
* You can still follow the mission instructions and complete the mission.

:stop_sign: Mission 6: NO NPC Pointers or Mission Dialog Window text.
* You can still follow the mission instructions and complete the mission.
* The CityAdmin Employee you _should_ be talking to, according to the dialog text is inside CityAdmin HQ. However, no NPC Pointers come up.  Running around the game world talking to "CityAdmin Employees", you get the mission dialog from a CityAdmin Employee in Pepper Park SEC-2 talking to a stripper, no NPC pointer appeared though.

**Comment by William-Antrim** [comment]
I have had this problem too. I will try to speak to the guy in PP2 and report back. cheers


edit: went back to mission and went to PP2 and found the guy talking to a stripper, so yes he still spawns ok in Pepper park 2. Epic was successfully completed.
