### ISSUE TITLE
mouse over xp values wrong on skills screen

### ISSUE THREAD

**Issue by hinch** [NCC-Lykos/neocron-classic#187]
Don't really know how to describe this but the skills screen seems to have a "static" xp value configured in it that is displayed when you mouse over in certain area's.  

So when you mouse over an actual xp bar it shows the correct xp value as you would expect just fine.
![neocron screenshot 2018 02 24 - 09 33 50 47](https://user-images.githubusercontent.com/2182589/36628894-be5cb482-1946-11e8-900e-01e5cd3750bb.png)

However if you mouse over the text for example
![neocron screenshot 2018 02 24 - 09 33 52 85](https://user-images.githubusercontent.com/2182589/36628899-d270be1e-1946-11e8-91da-668ba5a4afdf.png)
(in this case 704 is showing)

But it also shows if you mouse over  other parts of the screen...
![neocron screenshot 2018 02 24 - 09 34 04 15](https://user-images.githubusercontent.com/2182589/36628909-e9e4cb94-1946-11e8-8311-624755a9ae53.png)

**Comment by Darkeast** [comment]
the mouse MUST be over the exp bar to show the exp you need for a level up. If you mouseover for exemple the word Strength it´s show the exp you need for a int level up (also for dex psi-power and con)

**Comment by ghost** [comment]
Fixed.
-G
