### ISSUE TITLE
Spent points in BD & had malus shown

### ISSUE THREAD

**Issue by NCKryptonite** [NCC-Lykos/neocron-classic#194]
Just spent 50 points into hack while in battle dome, and it shows I have a -50 to hack. Relog corrected this.
![shot0010](https://user-images.githubusercontent.com/36805039/36648336-3366b7d6-1a60-11e8-96d8-cd409ddeccd7.png)

**Comment by NCKryptonite** [comment]
Noticed it just now in plaza 1 with a -50 to research. Nothing else.

**Comment by NCC-Therenall** [comment]
Closing to consolidate this with other outpost malus bugs: #297
