### ISSUE TITLE
Tsunami Syndicate - Epic Mission #3

### ISSUE THREAD

**Issue by thejohnwick** [NCC-Lykos/neocron-classic#196]
Mr Cook (Outzone 3) needs moving slightly. He usually dies with his feet inside the boxes making him untargetable. You can loot him by relogging in and hoping you can click him while he's standing before he falls down. After relogging in when he falls down his feet are usually inside the wall.

**Comment by butterrmahjely** [comment]
![shot0005](https://user-images.githubusercontent.com/6628124/36706079-37027f8e-1b36-11e8-9244-2dc430b0827b.png)

**Comment by ghost** [comment]
Fixed.  Watch patch notes for when this is patched in.
