### ISSUE TITLE
Tsunami Syndicate - Epic Mission #5

### ISSUE THREAD

**Issue by thejohnwick** [NCC-Lykos/neocron-classic#197]
Black Dragon Contact doesn't exist

**Comment by thejohnwick** [comment]
He does exist deeper within the BD faction office next to some 120/120 thugs that kill you in one shot... little bit cumbersome to kill - have to shoot then run to the zone line to deaggro and repeat or have someone else fire in a couple of grenades and run away - the NPC has a lot of health for a 40/40. Closed

**Comment by ghost** [comment]
I'm going to reopen this.  After watching a runner go through this, it's a bit too harsh. Sorry @thejohnwick for the confusion on this one.
