### ISSUE TITLE
TT Director of Operations (BT Epic)

### ISSUE THREAD

**Issue by NCKryptonite** [NCC-Lykos/neocron-classic#198]
Director should be showing as being in Tangent Tech faction since he's the Director of Operations for TT that you're killing for the epic, and he's supposed to be at the Chez Sypher restaurant in Via3, not the Chez Sypher in Via1, like the mission dialogue states. Killed this NPC, didn't accomplish the mission, lost 100 SL, and 50 symp.

![shot0014](https://user-images.githubusercontent.com/36805039/36768560-e0451296-1c0d-11e8-99ec-9eec722ee46a.png)

This is the only NPC besides the barkeeper at the Chez Sypher in via3, and there's no TT NPC or 'Director of Operations' anywhere in via3. Tried killing this NPC and still mission not accomplished,

![shot0015](https://user-images.githubusercontent.com/36805039/36768967-8834c662-1c0f-11e8-940a-a49fc62029d9.png)

**Comment by ghost** [comment]
That is the BioTech Director of Operations in Via Rosso SEC-1; as referenced by the Tangent Epic.

The location of the Tagent Director of Operations, for now, is inside Tangent HQ.  He'll be moved to his proper location in Via Rosso SEC-3 as per the BioTech Mission Text for the next patch.
