### ISSUE TITLE
Clan leader unable to activate GR in Clan Apartment

### ISSUE THREAD

**Issue by butterrmahjely** [NCC-Lykos/neocron-classic#199]
When trying to activate my clan apartment GR, I get the following error: "You are hostile to the local faction. Activation of this GenRep denied" (see [screenshot](https://gyazo.com/d7e293684ef9b71aad13a4063c4efea0))

Details:

Faction: Tsunami Syndicate
Area: Pepper Park 3 (Wendol A Lift)
Note: I am also the clan leader

**Comment by Stevil79** [comment]
Works for my clan leader at Tangent Clan Appartment.

**Comment by NCC-Atlas** [comment]
@Stevil79 reported:

"I was Tsunami and it said that I was a hostile faction when I tried to set my Plaza level 3 apartment as my primary for GR purposes. Dunno if it has been reported before. Please link if it has.

Not sure if its a bug that affects all factions but will test further."

This issue appears to not only deal with clan apartments, but standards as well.

**Comment by rhomm-dev** [comment]
This happens with the Black Dragon epic apartment as well (Pepper Park / Black Dragon)

![ncc_black_dragon_epic](https://user-images.githubusercontent.com/34965105/48804455-a7fdeb00-ece2-11e8-9763-75a5cfe41be0.png)

Possibly related I noticed the apartment also shows as "Unknown Location" on the web interface:

![ncc_unknown_location_bd_epic](https://user-images.githubusercontent.com/34965105/48925294-32378200-ee90-11e8-8f1a-6bf9a2452c32.png)

**Comment by ghost** [comment]
This is being fixed.
-G
