### ISSUE TITLE
Faction Mission and Terminal Mission have issues running together

### ISSUE THREAD

**Issue by NCC-Lykos** [NCC-Lykos/neocron-classic#2]
This is from a forum post

Repro Steps(I was in TG)

1. Go grab regular running mission like - kill x spiders
2. Go to Faction person and accept DOY mission
3. Abort DOY Mission
4. Mission list/window now empty, cannot abort previously held spider mission
5. Try to get new regular runner mission - IE: kill x cave crawlers

Results: Unable to accept another mission as game still registers original spider mission which player is unable to abort

**Comment by ncc-gnisha** [comment]
- [ ] Modify Header Dialogs for Mission Check

**Comment by ghost** [comment]
Just a minor update on this one.  The current missions have been fixed, just working on a permanent fix.
