### ISSUE TITLE
Xray bones not displaying bonuses to armor or CON

### ISSUE THREAD

**Issue by NCKryptonite** [NCC-Lykos/neocron-classic#200]
Per Gnisha, Xray bone bonuses should be getting applied as an armor bonus, but are not being displayed in the armor window. They ARE displaying the bonsues in the Implants window, but I'd say it should be displaying in armor, since it's adding to armor values. (So people know where it's being applied)

**Comment by Stevil79** [comment]
Not sure about this.

Piercing and Force resists show in your implant window if they come from bones. Same with resists gained from hearts. Why would Gamma be different?

**Comment by William-Antrim** [comment]
I agree with Stevil. If the buff comes from bones and chips (PPR/Moveon) it should stay in the implant window.

**Comment by NCKryptonite** [comment]
Additionally, I'd say the xray bones and frc/prc from bones should actually be adding to STR/CON stats...since they're bone enforcements and not clothes. They're needed in those main stats to reach getting the 101+ resist boosts on a PE or Tank.

**Comment by ghost** [comment]
This issue can now be closed with the rework of resists and the armor/bone/implant calculations. Bone resistances are being accounted for with the armor calculations.
