### ISSUE TITLE
Right Click/Show Info in Sell Menu does not work.

### ISSUE THREAD

**Issue by NCC-Atlas** [NCC-Lykos/neocron-classic#202]
Trying to right click an item when selling things brings up a blank info screen.

**Comment by ghost** [comment]
I can also confirm this.

**Comment by NCC-Therenall** [comment]
This works fine for me?

I'm able to right click -> show info on inventory items, buy items, and sell items no problem.

Can you guys re-test by chance?

**Comment by NCC-Therenall** [comment]
@NCC-Gnisha informed me this still happens, so I did more testing. Apparently the vendor I tested it on works. Only some vendors appear to have this problem.

**Comment by Darkeast** [comment]
Right Click/Show info DIDN´T open in Sell Menu

**Comment by ghost** [comment]
@NCC-Therenall: Trying this on one of the Cryton guys for example will duplicate this.

**Comment by NCC-Lykos** [comment]
This has been fixed for next patch.
