### ISSUE TITLE
RPOS Processor Progress Bar

### ISSUE THREAD

**Issue by thejohnwick** [NCC-Lykos/neocron-classic#203]
At the start of a construction process the rectangle gets drawn like this

![progress_bar](https://user-images.githubusercontent.com/36860966/36856658-7295e4ca-1d6e-11e8-9e36-5e005d27b3db.jpg)

**Comment by NCC-Atlas** [comment]
I can confirm this too, it seems to happen when you're building something that takes a very short time, for instance lower level weapons and weapon parts.

**Comment by NCC-Atlas** [comment]
![shot0007](https://user-images.githubusercontent.com/32750070/36857873-9ea9b536-1d47-11e8-926e-b73d8a3293e0.png)

**Comment by ghost** [comment]
Confirmed this is fixed.
