### ISSUE TITLE
Grenade Launcher Grenades

### ISSUE THREAD

**Issue by thejohnwick** [NCC-Lykos/neocron-classic#204]
...are able to be fired through solid objects

**Comment by Corruptforce** [comment]
Suspect this is a netcode issue? just like rockets appearing to fly in a certain direction on screen - but according to the server went a different way.

**Comment by thejohnwick** [comment]
Nope. I'll describe to a GM how to reproduce it if they're unable to.

**Comment by ghost** [comment]
So far I haven't been able to duplicate this.

@thejohnwick Can you send me the details on this through a DM on Discord and we can see if we can get this duplicated.

**Comment by ghost** [comment]
I still haven't been able to duplicate this problem and Wick hasn't DM'd me with steps to reproduce this.  Closing this for now.
