### ISSUE TITLE
Crashing everytime i zone

### ISSUE THREAD

**Issue by Amoney1** [NCC-Lykos/neocron-classic#205]
Since the last update, i have been crashing every time I zone. Polled OOC and others are experiencing the same issue. It's almost unplayable at this point. ty!

**Comment by ghost** [comment]
I feel your pain, I also crash on 98% of zone changes. 

Can you throw in some quick system specs? Operating System, Motherboard, RAM, video card, etc?

**Comment by Amoney1** [comment]
Actually, i ran the launcher as an admin and zone crashed practically stopped. The only issue I'm having now is tabbing out.

**Comment by NCC-Therenall** [comment]
Closing this as it's now an alt-tab bug.
