### ISSUE TITLE
npc missing from Diamond real estate HQ for epic

### ISSUE THREAD

**Issue by M-ace** [NCC-Lykos/neocron-classic#209]
There is an npc in the diamond RE epic thats missing.  Another runner raged last nite that a certain npc (I dont recall the npc's name) from the epic line who is supposed to be in the hq isnt there.

**Comment by ghost** [comment]
The only NPC that the Diamond Real Estate epic uses that is inside the HQ is the "Human Resources Director", and he's there.

**Comment by ghost** [comment]
I just ran though the DRE Epic on a local dev server and no problems.  Seems like this is another issue related to storage and the game isn't registering the proper NPCs to talk to, etc.

**Comment by M-ace** [comment]
u supposed to run it on our server NOOB!  :D

**Comment by ghost** [comment]
This is actually a duplicate of #160
