### ISSUE TITLE
Quest Contact - BioTech Director

### ISSUE THREAD

**Issue by NCC-Atlas** [NCC-Lykos/neocron-classic#210]
There is a BioTech Director both inside the Faction HQ, and one outside in a cafe. We need to decide which one to keep.

Currently, the NPC inside the HQ processes quest commands and the outside one just creates empty dialogue boxes.

Adding this issue just for records purposes.

**Comment by ghost** [comment]
We're keeping the BT Director of Operations that's in Via Rosso SEC-1.
