### ISSUE TITLE
Veh Condition and ammo not displayed

### ISSUE THREAD

**Issue by NCKryptonite** [NCC-Lykos/neocron-classic#211]
Occurs most of the time when I spawn the Heavy Assault Scorpion Trike, and never appears. The times it spawns showing the condition and ammo, it will eventually not be displayed after getting off and back on. Can't confirm yet if it's random or just after getting off the trike once.

**Comment by NCKryptonite** [comment]
Correction: Just reappeared after 20+ times of getting off and back on
EDIT: Now after a few more times, it's still displaying, but is a full mini-map length AWAY to the right of the mini-map.

**Comment by ghost** [comment]
I can confirm this.

With a Reveler, when I get into the vehicle I don't see condition, ammo, seats, etc.

**Comment by NCC-Lykos** [comment]
This has been fixed for next patch.
