### ISSUE TITLE
NEXT Epic - Few Things which needs to be changed or re-written 

### ISSUE THREAD

**Issue by stealthnoobwick** [NCC-Lykos/neocron-classic#212]
After completing the NEXT Epic, i gonna deliver some Things which might need to be edited. Decide, its up to you.

**Mission 4** - Required Rank: */35
![employee](https://user-images.githubusercontent.com/37018134/36934629-f9624f28-1eec-11e8-91b4-07bd9906b341.jpg)
Entering Via Sec. 1 there is no Arrow or Highlight on Contact Person, so change the Text or perform to Highlight that Person. By talking to all of them, i picked em up.
![next_epic_](https://user-images.githubusercontent.com/37018134/36934653-6c28d40a-1eed-11e8-9041-b61b084f3da3.jpg)

**Mission 5** - Required Rank: */40
![next_dennisk](https://user-images.githubusercontent.com/37018134/36934674-a7f55116-1eed-11e8-9611-ff8a421229b3.jpg)

It tells you the wrong Location. Mr. D. Karsten is located inside the Pussy Club, 
![dennis karsten](https://user-images.githubusercontent.com/37018134/36934727-fb7564ac-1eed-11e8-9ba9-848559a785ca.jpg)
![dennis karsten 2](https://user-images.githubusercontent.com/37018134/36934730-ff88c82c-1eed-11e8-9794-38158f2126ca.jpg)

Over both Missions i didnt had an Overview inside my Mission Window. Cleaning this Up didnt work too, but the Missions got accepted. It turned into normal at the last Part of the Epic (Part 6) Everything was displayed as it needs to be. 

![mission](https://user-images.githubusercontent.com/37018134/36934748-56ad4fe2-1eee-11e8-875b-9b50835a52bc.jpg)

**Comment by ghost** [comment]
Thank you for the detailed report @stealthnoobwick 

**Mission 4** - Required Rank: */35
_The "NPC Pointer" not showing up is currently a confirmed bug that the team is getting sorted out._

**Mission 5** - Required Rank: */40
_In the next patch, the mission text has been updated to reflect his location.  As for the Wiki, it's a community wiki, anyone can create an account and edit content. I have made this correction though._

**Mission Window Dialog**
This is bug that has been reported in Bug #144

**Comment by ghost** [comment]
Closing this report as detailed information has been added in Issue #186
