### ISSUE TITLE
Special Forces Plasma Wave Not usable

### ISSUE THREAD

**Issue by cptYokom** [NCC-Lykos/neocron-classic#220]
I just move my Tank Rampart to City Admin wanted to test out the Faction weapon Plasma Wave. It has two slots and looks shiny as in not red so the game thinks I can use it. 

But it wont mod
Cant load ammo
Cant even get it to equip, it goes in the slot but wont pull out. 
No description in the show 

There was a forum post closed about it with no word on if it is usable in game.

**Comment by NCC-Lykos** [comment]
So those were NC2 items. They need to be removed from game.

**Comment by ghost** [comment]
This item along with the Special Raygun Cannon have been removed. Watch patch notes for when this is patched in.
