### ISSUE TITLE
Protopharm Epic

### ISSUE THREAD

**Issue by AdrianB291** [NCC-Lykos/neocron-classic#221]
2 minor issues with the protopharm epic. 

Firstly when you are tasked by morpheus to kill fallen angels employees you are not told how many. Killing one, two or three doesnt show a mission complete message. this is stage 3 i believe.

Stage 5 when you are tasked to kill the tsunami pimps. Max says kill one. I had to kill 3. the mission text came up with the "only need 2 more..."

**Comment by ghost** [comment]
With Mission 3, there is an issue where the mission dialog text doesn't properly display.  That is being worked on in another issue.

As for the mission where you have to kill the 3 Tsunami Pimps, I will look into that.

**Comment by ghost** [comment]
I've fixed the number of Tsunami Pimps that you have to kill for this mission, it will be set back to one to match the mission text.

Will be in the next patch, watch the patch notes.
