### ISSUE TITLE
Mutant Gunman

### ISSUE THREAD

**Issue by AdrianB291** [NCC-Lykos/neocron-classic#222]
Power is too strong. Range maybe too. They need to be looked at from a new player pov because currently they feel more powerful than most of the other mobs around that level. 3 of them together shooting at you is instant death. Tone down the range and/or damage they can hit with. bring them more in to line with other mutants around that level.

**Comment by Corruptforce** [comment]
Their range is definitely longer than a sensible flamethrower range would be.
I think the damage is fine, it's just that not many lower levels are rolling with Fire Resist gear.

One way to make them more noob friendly, might be to split their damage from Fire (assuming it's pure fire) to Fire/Force?

**Comment by M-ace** [comment]
their damage is definitely not fine.  it doesnt even matter if u have fire gear or not.  wheather u are 0/2 or /50 THAT mob will be your first target whenever they are present in aggies.  so for their level and where they are, they are out of line.

**Comment by AdrianB291** [comment]
Agreed with Mace. 

3 of them together was instant death to my pe at rank 40+ and shelter up. They need to be looked at in the grand scheme of things. The damage needs to be toned down considerably. Anyone saying otherwise is sadly misguided. I realise this is more of a feature than a bug but all the same it stands out as a beta issue.

Adding the burning effect like the enlightened preachers would also signify damage being taken by the player visually. given the range they can hit at it this is a worthy consideration.

**Comment by NCC-Lykos** [comment]
This was an issue with resists. Test again and report back if still an issue.
