### ISSUE TITLE
Stuck texture Tank Stuck in hole

### ISSUE THREAD

**Issue by cptYokom** [NCC-Lykos/neocron-classic#223]
Just a part of the world you can get it but cant get out. In I-14 sector 
![stuckbada](https://user-images.githubusercontent.com/36430896/37238422-c1348770-241d-11e8-9f29-ef72b9f4449b.png)

**Comment by NCC-Lykos** [comment]
He who drives his tank into a hole, deserves to get stuck. Not a bug really, just poor choice in driving :P
