### ISSUE TITLE
Implant vendor for hearts

### ISSUE THREAD

**Issue by AdrianB291** [NCC-Lykos/neocron-classic#224]
Found another issue today guys. 

Crytons Tech tools is selling 2 hearts which are basically the same. The strengthen heart 1 and 2 and the Advanced heart 1 and 2 have identical stats at the respective levels yet one is a slightly lower TL than the other. Seems pointless and might be worth removing one from the vendor menu.

**Comment by ghost** [comment]
Advanced Heart 1:
* CON +1, Endurance +5, Resist Poison -8

Advanced Heart 2:
* CON +3, Endurance +10, Resist Poison - 15

Strengthen Heart 1:
* CON +1, Body Health +5, Resist Poison -8

Strengthen Heart 2:
* CON +3, Body Health +10, Resist Poison -15

I don't see any of these that have identical stats?

**Comment by AdrianB291** [comment]
apologies. I misread the endurance in it. Sorry. I will pay closer attention before filing.
