### ISSUE TITLE
Battle dome vendors

### ISSUE THREAD

**Issue by AdrianB291** [NCC-Lykos/neocron-classic#225]
Battle dome vendors do not work. Only one has an active menu and the products sold do not match the description. Its the middle one facing north. i forget the name of it. 

all others say vendor is busy.

**Comment by butterrmahjely** [comment]
Cycrow Lab and Chester Lab have vendors that don't work either

**Comment by ghost** [comment]
Reference Issue #85

**Comment by ghost** [comment]
Fixed.
