### ISSUE TITLE
SL gain from mission(s) too high

### ISSUE THREAD

**Issue by NCKryptonite** [NCC-Lykos/neocron-classic#227]
Only noticed it with TSU from last night so far, but ill try other factions. I went from 42 SL to 100 SL after 4 small sewer rat missions for TSU. Was gaining about 18 SL from each mission with the chat log saying I gained a "great deal of soullight".

**Comment by thejohnwick** [comment]
Yup, except this isn't a "bug", just an incorrect setting. Not sure what category you would dump it in as it's not quite balancing but loosely associated with PvP.

**Comment by AdrianB291** [comment]
On a similar note the epics arent rewarding faction symp for completion. The Soullight and sympathy thing is something to tweak together down the line

**Comment by NCC-Therenall** [comment]
@NCC-Lykos is this actually a storage bug or something for balance/content?

**Comment by NCC-Lykos** [comment]
Not totally sure. Popped up after storage iirc. Needs troubleshooting to make sure.

**Comment by Darkeast** [comment]
got 5 SL for 1 Aggressor Captain mission

**Comment by NCC-Therenall** [comment]
This *may* have been fixed by a bug fix I did tonight for the negative SL. Please try again after tomorrows patch.

**Comment by ghost** [comment]
I completed 3 Aggressor Captain missions, and I've received 1 SL per mission.
