### ISSUE TITLE
Unidentifed Object UFO 

### ISSUE THREAD

**Issue by stealthnoobwick** [NCC-Lykos/neocron-classic#228]
Lonely as Fuck, it asks to be removed

Sector H-08 - Numpad 5
![4](https://user-images.githubusercontent.com/37018134/37247421-f7868ae2-24ba-11e8-8e9b-bc013ac9aa00.jpg)
![1](https://user-images.githubusercontent.com/37018134/37247422-fc2dcf88-24ba-11e8-8dbf-371aad4c254f.jpg)
![2](https://user-images.githubusercontent.com/37018134/37247425-ffc7ced2-24ba-11e8-9eb9-6f1efaa17882.jpg)
![3](https://user-images.githubusercontent.com/37018134/37247427-03e98230-24bb-11e8-973d-8aa951fddc8a.jpg)

**Comment by ghost** [comment]
Already fixed for next patch.
