### ISSUE TITLE
Windowed Mode 

### ISSUE THREAD

**Issue by Corruptforce** [NCC-Lykos/neocron-classic#233]
Issues running Windowed Mode on 1920x1080.

Everything is slightly skewed and not quite clear, I remember this used to be fixed (mostly) but editing font sizes within fonts.ini - however this doesn't seem to exist any more.

Possible there's scope for implementation of a borderless Windowed Mode, or are there currently any workarounds? without having to step down the resolution.

**Comment by NCC-Lykos** [comment]
There is a current workaround for borderless window mode, and that is by getting that app borderless windows, it works well with NC actually.

**Comment by Corruptforce** [comment]
I'll give it a try when I've got access to a client - thanks for the tip.

**Comment by Corruptforce** [comment]
Works well.

Although still suffering from a bit of jaggedness on the text/reticle.
