### ISSUE TITLE
Crashes when using Inv/QB

### ISSUE THREAD

**Issue by William-Antrim** [NCC-Lykos/neocron-classic#236]
Apologies if this has already been posted - im new to this. 

I have had random crashes to desk top when poking implants into my head (moveon chip) and when transferring armour/items to their respective slots on my paperdoll/quick belt. 

This has happened at least a half dozen times over the weekend of play.

**Comment by Corruptforce** [comment]
Hi William,

Are you able to reproduce this consistently? I can't say I've had many crashes, especially when doing inventory/processor stuff.

**Comment by William-Antrim** [comment]
Nor have I. I think i have had 2 or 3 over several hours of playing so no i cant reproduce it reliably i am afraid. It has happened once when equipping armour, once when trying to cast a spell and once when trying to implant a brain chip. I dont think it is a big deal but it was enough to mention so it was recorded.

**Comment by Corruptforce** [comment]
Unfortunately very hard to track down those sorts of issues, I'm not sure if NC has some kind of crash log which can be submitted?

**Comment by William-Antrim** [comment]
ive been able to force the client to crash when i right click on an item to use it (prior to selecting the activate button for medkits for example) and then press tab to close the rpos. i dont know if this is related or helps but it was all i could find for now.

**Comment by NCC-Lykos** [comment]
We cannot reproduce this, so may be fixed.
