### ISSUE TITLE
Appartment Doors

### ISSUE THREAD

**Issue by ghost** [NCC-Lykos/neocron-classic#24]
- [ ] many app doors are buggy sreenshots can be find in forum thread https://forum.neocron.org/threads/533-Appartment-Doors

**Comment by NCC-Camarogue** [comment]
Some doors having no hitbox is intentional and adds to the overall atmosphere.
About the clipping issues.. well i fixed one so far, but it'll have to wait until we start the bsp cleanup phase.

**Comment by ghost** [comment]
@NCC-Camarogue  Some doors having no hitbox is intentional and adds to the overall atmosphere......
 i dont think so ... Some doors of the same skin in the same area got a hitbox and some doors not ( left side of a appartment got a hitbox the right side got no names ) thats what i mean....

**Comment by ghost** [comment]
- [ ] tech haven appartment doors are to small... you get stucked very easy in the wall when the door close. i think new player will get stuck each time they will leave/enter a appartment and i dont think they will know the command /set reset_position 1.. in th sec 1 the appartment doors got another skin.. maybe replace them in th sec 3 with the door skin from sec1 ?
![shot0000](https://user-images.githubusercontent.com/32795552/32805444-bd5d2222-c989-11e7-9345-c3c90e1f7ac3.png)

**Comment by ghost** [comment]
the proto pharm hq entrance door in via sec 2 does not open correctly(the door is only half open and close very fast)
![shot0001](https://user-images.githubusercontent.com/32795552/37467963-8ec6d974-2859-11e8-955c-1e13788ad908.png)

**Comment by ghost** [comment]
#269

**Comment by ghost** [comment]
Apartment Doors in Via Rosso SEC-3 -- Reference issue #269

**Comment by ghost** [comment]
#275

**Comment by NCC-Lykos** [comment]
As the forum thread is gone, I have fixed the Viarosso doors and the Tech Haven doors will wait until a redesign.
