### ISSUE TITLE
Implant - Not Activating Correctly

### ISSUE THREAD

**Issue by Corruptforce** [NCC-Lykos/neocron-classic#240]
I logged out whilst having an implant process in progress.

Next time I logged in, I was unable to use any of my HC weapons.
Grabbed some lower level ones, and they seemed fine.

Char sheet showed 87 STR (+14) and I was unable to use a TL 84 weapon.

Right clicking and viewing info on the weapon showed that I had enough STR to use (STR highlighted in gold to indicate I was able to use after modification of stats via implants).

Investigated by pulling out each STR implant one by one and placing back.
Lastly, got to my backbone. After putting it back in, it resolved the issue.

Seems like interrupting the implanting process by logging out during allowed the implant window to show my backbone was in and working, show the stats I should have - but not actually give me the +4 STR I needed.

**Comment by NCC-Lykos** [comment]
Cannot reproduce at this time. Closed.
