### ISSUE TITLE
Next Epic - Almachin dialogue

### ISSUE THREAD

**Issue by William-Antrim** [NCC-Lykos/neocron-classic#244]
The guy at El farid village for next epic mission 4 (i think) - he has about 3-4 typos in his text. Not a huge problem admittedly but mildly annoying.

**Comment by ghost** [comment]
I've gone through all of the epics recently and fixed up a huge number of typos, etc.  Do you recall what in particular was wrong so I can double check it?

**Comment by William-Antrim** [comment]
No honestly i didnt think to record them beyond making a note. One of them was an "I" instead of an "In" or vice versa and the other two stood out to me quite easily. The best I can say is if you can access the scripts and post them here perhaps I can quote them and highlight the bits I was referring to in bold or something?

**Comment by ghost** [comment]
I did make a lot of changes, including to that particular section of the NEXT Epic with that NPC. I've double checked the text and it looks alright now. All the changes should be in the next patch.
