### ISSUE TITLE
BlackDragon Secret Faction Ofiice NPC Spawnpoint 

### ISSUE THREAD

**Issue by ghost** [NCC-Lykos/neocron-classic#250]
i found a bad spawn point for a npc in the black dragon secret faction office! it is at the entrance to pp3 see screenshots
![shot0000](https://user-images.githubusercontent.com/32795552/37572549-af31ce8c-2b04-11e8-9838-5757015a0213.png)
![shot0001](https://user-images.githubusercontent.com/32795552/37572550-af5776c8-2b04-11e8-82ec-46a90c34294b.png)

**Comment by ghost** [comment]
I've double checked this, and the NPC placement is fine.  That NPC that's standing in the doorway is from the NPC chasing after a runner who has left the zone, and due to the AI he hasn't returned to his usual position.

**Comment by hazuk** [comment]
i shoot him and tested he is walking back every time to this buggy place.. remove him! i test think before i report......
