### ISSUE TITLE
Crahn HQ(pp3) NPCs/Trader

### ISSUE THREAD

**Issue by ghost** [NCC-Lykos/neocron-classic#252]
there are 4 npcs in the crahn hq named scientist they sell nothing!! the npc named father agnus is buggin on a table!! and the guard at the end of the hall is watching the wall all day long! see screenshots

4 scientist npcs
![shot0004](https://user-images.githubusercontent.com/32795552/37573379-25cd6204-2b0f-11e8-9abe-81874a4ccad6.png)
![shot0000](https://user-images.githubusercontent.com/32795552/37573380-2651e448-2b0f-11e8-9de7-ad00dcfff680.png)
![shot0002](https://user-images.githubusercontent.com/32795552/37573381-2679d3a4-2b0f-11e8-8525-58e3a3ba2544.png)
![shot0003](https://user-images.githubusercontent.com/32795552/37573382-269ec7c2-2b0f-11e8-8c13-19fee3e439f7.png)

guard at the end of hall
![shot0005](https://user-images.githubusercontent.com/32795552/37573386-2cbe5532-2b0f-11e8-882d-77eb59c8fdb4.png)

father agnus on the table

![shot0001](https://user-images.githubusercontent.com/32795552/37573392-38614d86-2b0f-11e8-9120-7f4928745406.png)

at the entrance in pp3 standing many crahn guards.. one of them cant reach his place maybe remove some of the guards ?? 2 guard at the entrance would be enough ?!
![shot0007](https://user-images.githubusercontent.com/32795552/37573497-653bd122-2b10-11e8-9b84-d8a7524865f4.png)

**Comment by ghost** [comment]
Father Agnus was left over from some of my testing.  He has been removed from the sector.

The Inquisitors that are guarding the entrance have been respawned in their proper locations. When the NPCs chase a runner down they don't always go back to their starting position properly. This isn't an issue with NPC placement, it's an issue with the pathing of the NPC. 

Still working on the other points in this issue.

**Comment by ghost** [comment]
When the NPCs chase a runner down they don't always go back to their starting position properly. This isn't an issue with NPC placement, it's an issue with the pathing of the NPC.

@NCC-Gnisha thats why i reported it... why dont you remove the guys upstairs? so they cant end up in a pathing issue O_o 2 guard down at the door is enough for real this guys instant kill you with this op spells ^^

**Comment by ghost** [comment]
I'm not going to delete any of the guards. It's more than just "having enough force to kill a runner", but its also a presence of the guards in front of the HQ.  Also, just deleting NPCs that run into pathing issues, we'd be deleting 75% of the NPCs in this game.  Just not a viable option.

**Comment by hazuk** [comment]
Also, just deleting NPCs that run into pathing issues, we'd be deleting 75% of the NPCs in this game.

give me a tool or acces and i do it and set some new spawn points too :D  its your game... your choices... i only wanted to help to make the game better.. only a question how long does it take to set a new spawn location 1min max i think??

**Comment by ghost** [comment]
Reference Issue: #184

**Comment by ghost** [comment]
Closing this as the placement for the Grand Inquisitor has been fixed for the next patch, and the scientist NPC dialog is a duplicate of Issue #184 .
