### ISSUE TITLE
NPC/MOB - Tech Haven Turrets

### ISSUE THREAD

**Issue by Corruptforce** [NCC-Lykos/neocron-classic#253]
Fairly noticeable that the range on most Laser based mobs is insane.
Notably the Tech Haven Turrets, seem to be able to aggro from half the map away - now considering some of these turrets are at OP zones, being an enemy of FA means these are no go areas.

I can be dropped in 4 hits by a turret which is beyond my draw distance.

**Comment by NCC-Lykos** [comment]
#214
