### ISSUE TITLE
plaza 1 missing window

### ISSUE THREAD

**Issue by ghost** [NCC-Lykos/neocron-classic#256]
there is a missing window in the inside from the building  plaza 1 see screenshots

inside
![shot0002](https://user-images.githubusercontent.com/32795552/37631926-b3a07c40-2be3-11e8-94c1-9dc21742de9a.png)

outside
![shot0001](https://user-images.githubusercontent.com/32795552/37631933-b7f4562c-2be3-11e8-9fee-189f4d37a6cb.png)

**Comment by M-ace** [comment]
the window is there, its not like u can jump thru it.  its just invisible looking from one side

**Comment by NCC-Lykos** [comment]
Fixed pending patch 63
