### ISSUE TITLE
Music/Sound - Military Base

### ISSUE THREAD

**Issue by Corruptforce** [NCC-Lykos/neocron-classic#257]
Quite an old issue, but worth raising a ticket for.

Can we get the music volume normalised in MB? It's somewhat nauseating how loud it is currently.

I think it has always been this way, but would definitely enable me to hang out there more often!

**Comment by ghost** [comment]
#110

**Comment by Corruptforce** [comment]
@hazuk Not quite related - I don't mind the music, but even with the sound settings set to very low, it is way louder than it should be,

**Comment by ghost** [comment]
I agree with this one.  Other zones the music and background noise it at one volume, you go here and noticeably louder than the rest of the zones.

**Comment by Xtro1** [comment]
Maybe the MB NPC's like it that way when i try to talk to them sometimes they seem deaf

**Comment by ghost** [comment]
Going to close this out now we've unveiled the new Military Base SEC-1.
