### ISSUE TITLE
RPOS Window Help Dialog

### ISSUE THREAD

**Issue by thejohnwick** [NCC-Lykos/neocron-classic#265]
If you click on any ? it creates the dialog but it cannot be dragged and there's no close button.
![dialog](https://user-images.githubusercontent.com/36860966/38102223-86e80580-337a-11e8-9abe-03a177661eaf.png)

**Comment by thejohnwick** [comment]
Just to add a note when in an apartment I just noticed the dialog works correctly. The close button is there, contains the text, and the window is draggable (I guess the RPOS is recreated upon every zone and possibly the cause of many zone crashes?)

**Comment by NCC-Lykos** [comment]
This has been fixed for next patch.
