### ISSUE TITLE
Vendor in Viarosa

### ISSUE THREAD

**Issue by Xtro1** [NCC-Lykos/neocron-classic#266]
so while am waiting the increastime to poke my moveon back in i thought i would come and relate vender missmatch in Viarosa sec 2  in the three booths  of crytons 2 of the vendors sell exactly the same items but the vender selling  research lube and  implant gel  items is missing
i can write more  Moveon still going in  who do i report above matter too.

**Comment by ghost** [comment]
Not sure what happened with this.  It's showing in my list as being fixed awhile back.  Will get this taken care of, though.

**Comment by ghost** [comment]
Fixed.  Watch patch notes for when this is patched in.
