### ISSUE TITLE
Doors - Via Rosso 3

### ISSUE THREAD

**Issue by thejohnwick** [NCC-Lykos/neocron-classic#269]
Two of the apartment lift doors at Alamo Livings act like two separate door panels, and don't open as a pair. When you open one of the lift doors it also opens one or both of the other lift doors in the same row.

Hazuk noticed this but he didn't want to attempt describing it in English... :D

**Comment by ghost** [comment]
Closing this for now, since this bug is now referenced in the "Apartment Doors" issue. Lets see if we can get a list together of all the apartment doors that need work done to them and post them in Issue #24 .
