### ISSUE TITLE
OUTPOST BONUS BUG (fortresss) : weapon not useable after zoning

### ISSUE THREAD

**Issue by replicatorjoe** [NCC-Lykos/neocron-classic#271]
after zoning form H11 (blackhill)  to h12 my heavy weapons become unuseable. chat tells me "you cannot use this item yet"  
zoning back, weapons become useable again.  ( yes, i meet the requirements! )   

hint: maybe permanent outpost bonus / malus?

**Comment by replicatorjoe** [comment]
left h12 to  tezla sector -> weapons useable again

went from tezla sector back into h12  -> weapons still useable

MUST BE OUTPOST BONUSES doing BULLSHIT

**Comment by ghost** [comment]
Reference Issue #171

**Comment by NCKryptonite** [comment]
Similar issue when I pass through Chester zone. I get a -50 to research, and even after passing 2 more zonelines and GRing to plaza 1, I still have the research malus. Have to relog to remove it.

**Comment by NCC-Therenall** [comment]
Closing to consolidate into #297
