### ISSUE TITLE
Protopharm Epic Step 2

### ISSUE THREAD

**Issue by Stevil79** [NCC-Lykos/neocron-classic#272]
George is listed as being somewhere in the lab according to the mission text but he is actually in Protopharm HQ. Mission Text needs updating as George shouldn't be in the same place as Mikhail due to Mikhail working for a different department in the faction.

**Comment by NCC-Atlas** [comment]
eh @NCC-Gnisha yeah that makes sense.

**Comment by ghost** [comment]
I'll go through that mission text again and make some changes, etc.

**Comment by ghost** [comment]
Fixed.  Watch patch notes for when this is patched in.
