### ISSUE TITLE
Viarosso 2 Appartment Doors are buggy :)

### ISSUE THREAD

**Issue by Skansy** [NCC-Lykos/neocron-classic#275]
Hi there ... the 3 Appartment Doors next to the Subway entrance are a bit strange :)

Left door:
- both door-parts open when clicking the left or the right door-part 👍 

Middle door:
- only the door-part i click open, the other stay closed
- when clicking one of the door-parts, both door-parts from the left appartment lift and the left door-part of the right appartment lift open

Right door:
- only the door-part i click open, the other stay closed

Video:
https://www.twitch.tv/videos/245350840

**Comment by ghost** [comment]
Closing this as it's a duplicate issue since we already have an entire issue thread going about apartment doors in Issue #24 - This issue has also been referenced there.
