### ISSUE TITLE
Gaia Mine - S.T.O.R.M. BOT

### ISSUE THREAD

**Issue by cptYokom** [NCC-Lykos/neocron-classic#277]
There is something wrong here. You get to the 120 stormbot and then when you shoot him with  a full camo armor tank with full PPU buffs and a heal on you, he kills you in 3 seconds and he isn't even in sight. I just tossed in two cannon shots and boom dead. It even has an aoe affect since it killed the ppu that was just a few feet behind my tank. They both dropped in 3 seconds after I opened fire. Didn't even get the 3rd shot off from the raygun cannon. 

Not sure what is going on here but his damage used to be rough but its insane now and he shoots through walls and one shots people. I know I went there with a group of 2 or 3 and was able to get the storm laser back in the day so to speak.

**Comment by brawl-uk** [comment]
Much like the mobs at mc5 and a lot if not most 120/120 mobs. PPU can't  defend its self let alone anyone else right now

**Comment by NCKryptonite** [comment]
Might be related to the shot-out body section dmg. Any dmg done after the section of the body is shot-out does a ton more. That & health-bounce isn't helping.

**Comment by NCC-Lykos** [comment]
This should be fixed now that resists are fixed.
