### ISSUE TITLE
FA runner missions 

### ISSUE THREAD

**Issue by brawl-uk** [NCC-Lykos/neocron-classic#280]
I noticed that as a FA runner the city com offers a lot of TH based mobs for kill missions but couldn't find any mutant or aggressor missions.

**Comment by ghost** [comment]
With Fallen Angels being based in Tech Haven, it would only make sense for the majority of the missions to center around that area.  For example, Twilight Guardian terminal missions are with mobs based around the Canyon area (crawlers, crunchers, etc) -- Basically your Canyon Cave mobs. The Fallen Angels missions are with mobs that are found in the Tech Cores.

To get mutant-based missions, you would have to pick a Pro-City faction that you wouldn't mind gaining some sympathy with and going that route.  You'd still gain Soullight and experience points.
