### ISSUE TITLE
Electroshocker TL

### ISSUE THREAD

**Issue by Swine95** [NCC-Lykos/neocron-classic#281]
Electroshocker STR 32 MC 65 TC 40  is listed in description as TL 53 at A&W Advanced Melee Weapons Plaza 2

**Comment by ghost** [comment]
@Swine95 That information, are you comparing that to information on the Wiki?

**Comment by Swine95** [comment]
The Wiki lists the correct TL of 32. I was reading the item description under show info at the store itself. Also , the Unlabeled Electroshoker STR 15 MC 37 TC 18 is described as TL 29 at the store  when  you right click it and select show info.

**Comment by Swine95** [comment]
The Unlabeled Electroshocker is properly listed on Wiki as TL 15

**Comment by ghost** [comment]
The data provided by items in-game overrides what the Wiki states.  Once I get a new ItemsDB up and running, the wiki will match what the game says.

**Comment by Swine95** [comment]
It's just that the mismatch in this case is at the in-game level as both electroshokers are listed at higher TLs in-game than their respective in-game primary STR stats. Anyway just wanted to point that out.

**Comment by ghost** [comment]
Gotcha, so basically the Item TLs arn't matching the primary stat requirement.  There are _a lot_ of items like this in the game and these will be looked at during balancing.  One of the spreadsheets I'm working on will aid us in this.
