### ISSUE TITLE
Special forces cpu 

### ISSUE THREAD

**Issue by brawl-uk** [NCC-Lykos/neocron-classic#282]
The +10 hack bonus doesn't appear to be working on the chip

**Comment by ghost** [comment]
I equipped this CPU to my runner and all of the bonus' listed on the chip took effect.

Did you try relogging to see if that solved it?

**Comment by brawl-uk** [comment]
Didn't think to try that I will keep you posted

**Comment by brawl-uk** [comment]
Bonus is working correctly now

**Comment by ghost** [comment]
Awesome. Thanks for letting us know.
