### ISSUE TITLE
embedded benchs?

### ISSUE THREAD

**Issue by M-ace** [NCC-Lykos/neocron-classic#283]
theres a  bench in the water fountain outside city admin hq

![shot0098](https://user-images.githubusercontent.com/35941858/38397634-9a554f14-38f3-11e8-9507-2461c49d0994.png)
![shot0097](https://user-images.githubusercontent.com/35941858/38397636-9dfdf24c-38f3-11e8-99e0-63a1dc6956a4.png)
![shot0096](https://user-images.githubusercontent.com/35941858/38397639-a0dee930-38f3-11e8-9805-c93d7018dc7a.png)

**Comment by M-ace** [comment]
also, u get stuck on this bench and have to reset position to get out of it.  u also can see the npc's on the other side of the fountain

**Comment by ghost** [comment]
#159
