### ISSUE TITLE
Military Base

### ISSUE THREAD

**Issue by Xtro1** [NCC-Lykos/neocron-classic#284]
Any chance of an update to the Military base retail area I think by now they would have gotten around to putting a lift or maybe an escalator in.  
As it is one of the zones has its ladder on the wrong side ...likely an error due to duplicating one side on the other, for me, it just feels wrong to have ladders down to retail zones coming back up with your arms full of shopping could have serious consequences.

**Comment by ghost** [comment]
The GitHub _Issue_ Tracker is for reporting Issues and Bugs.  To make suggestions for improvements of various areas of the game, use the Brainport on the forums: https://forum.neocron.org/forums/16-Brainport
