### ISSUE TITLE
Gel Use Bugged

### ISSUE THREAD

**Issue by ghost** [NCC-Lykos/neocron-classic#287]
Setup:
Heavy Combat Eye 3, 1 Pack of Implant Gel

When you go to implant this Eye, it takes 13 units of Gel, leaving you with 7.  Cancel the implant process, re-implant it and it takes takes the remaining 7 units of gel and starts the implant process, even though it "requires" 13 units.

Also, if you have multiple containers of gel, it will finish off a container without taking units from the next.

This happens with any implant that uses gel.  The Heavy Combat Eye 3 was just a use case.

This was brought up by John Wick, I've confirmed we have this issue on our server as well.

**Comment by ghost** [comment]
Just to add to this, it's not storage related at this happens on the _other_ Neocron, too.

**Comment by ncc-zodiac** [comment]
Flawed tool gel usage algorithm rewritten. fixed.
