### ISSUE TITLE
No Healing from Beds

### ISSUE THREAD

**Issue by Stardustger1** [NCC-Lykos/neocron-classic#291]
the recreation Units in the Medi and the Beds in apartments don't actually heal you.
Your healtbar will change color like you used a medikit but your healt will not actually be healed

**Comment by ghost** [comment]
Not sure if this is a source bug, or related to the storage bugs.  So I've assigned both labels to this for now.

**Comment by NCC-Therenall** [comment]
Just fixed this on our side. 

I also found that health gain from healing sources was not properly being affected by run/walk/sit/swim mechanics. Same goes for drug flash dissipation. All of these should also be fixed on our end now. 

This will go live next patch. Going to close this for now.
