### ISSUE TITLE
Tangent Epic mission 6

### ISSUE THREAD

**Issue by Stardustger1** [NCC-Lykos/neocron-classic#292]
in mission 6 when it talk to andressa the mission doesn't actually progress
i can just repeat the dialog over and over again
killing the director does nothing and the mission just stops there

i have aborted and restarted the mission 3 times now

**Comment by Stardustger1** [comment]
Issue solved there is a second version of the director you have to kill inside the HQ now the 1st version sitting in the restaurant like in the mission text doesn't work for the epic anymore

**Comment by ghost** [comment]
I've removed the BioTech Director of Operations from the HQ, _again_.  Will double check the world files to make sure he's really gone.

**Comment by ghost** [comment]
I've double checked the zone files for the BioTech HQ and I've ensured that he is indeed removed.
