### ISSUE TITLE
Creeper Inc NPC gives infinite Master Glove

### ISSUE THREAD

**Issue by kalonji64** [NCC-Lykos/neocron-classic#295]
Hello Lykos,

I noticed the NPC in plaza1 that gives the Master Tradeskill Gloves seems to be bugged : indeed every time I reconnect or at least once a day he gives me another...   I created my runner yesterday (Runner "Kalon G" on the account "Kalonji") and he already has 3-4 gloves, so I thought I'd advise   :)

Regards,

Kalonji

**Comment by ghost** [comment]
If you don't have another glove in the inventory, it'll give you as many as you want.  Not really concerned about this as he's just a temporary NPC and won't be used outside of beta.
