### ISSUE TITLE
RPOS Is not fully converted to NC1

### ISSUE THREAD

**Issue by NCC-Lykos** [NCC-Lykos/neocron-classic#3]
I am working on the RPOS Rollback to NC1. This is the progress...

- [x] Hypercom
- [x] Inventory
- [x] Implants
- [x] Armor
- [x] Skills
- [x] Factions
- [x] Processor
- [x] Missions
- [x] Nav-Ray
- [x] Team
- [x] Options
- [x] Misc Dialogs
- [x] Expand Location Namespace

**Comment by NCC-Lykos** [comment]
Updating this, we are almost done with our RPOS rollback.

**Comment by ghost** [comment]
will you remove the recover backpack button at the genrep ? and why is there a message in the skills wisdom of ceres : NOPE ?? :)
