### ISSUE TITLE
possible Construction bug

### ISSUE THREAD

**Issue by ronmcsw** [NCC-Lykos/neocron-classic#300]
ive got a bp of a hovertec key and the 4 required parts which the bp says are required a tl75 construction tool and grease,
but when i try to construct it wont do it and it says i require more parts check the bp
![image](https://user-images.githubusercontent.com/32025637/43848182-52add52a-9b2a-11e8-8185-f7a0a475306c.png)
![image](https://user-images.githubusercontent.com/32025637/43848385-bb0df24e-9b2a-11e8-8f60-d88350c259d1.png)
the first image shows the parts by number in the inventory next to the notation showing whats needed.
the second shows the results in chat after several tries to construct the hovertec vehicle key is this the correct way to report a possible bug i apologise if its not sincerley TStark

**Comment by ghost** [comment]
@ronmcsw 

You're not using the correct parts to build the item.  In your screenshot you have items with a "V#" tag on them.  Those are "Next Vehicle Componentparts".  You should be looking for "NEXT Vehicle Component" parts with a "C#" tag.

**Comment by ghost** [comment]
Also something to add here since a lot of newer players may not be aware of it.  In order to get Item Parts 8-10, you have to recycle 2 of the lower level ones (i.e. 2x Number 7 Parts = Number 8 part; 2x 8 Parts = 9 Part).
