### ISSUE TITLE
ATTN: NCC-Gnisha (TT Epic Mission 6)

### ISSUE THREAD

**Issue by Robo-Combyte** [NCC-Lykos/neocron-classic#301]
I noticed in an earlier issue where the "Director Of Operations" was intentionally removed from Biotech HQ out in the open of Via Sec-1 into a sector which is now secure here: 
https://github.com/NCC-Lykos/neocron-classic/issues/292

Unable to draw my weapon, this makes the TT Epic impossible.

![shot0005](https://user-images.githubusercontent.com/42428000/44186502-60facb00-a0df-11e8-9d32-4e2bd7f1008f.jpg)

**Comment by ghost** [comment]
@Ravvex I've reset the flags on Via Rosso SEC-1 and Via Rosso SEC-3.  Can you please confirm that you're able to complete this epic?

**Comment by Robo-Combyte** [comment]
@NCC-Gnisha Yes, i was able to complete the epic after the sector was changed! Thank you very much!
