### ISSUE TITLE
Repairing lowers Dexterity

### ISSUE THREAD

**Issue by Squooshie** [NCC-Lykos/neocron-classic#302]
As shown in the attached screenshot, I repaired my hovertec which caused my dex skill to drop from 14 to 0.

![repair bug](https://user-images.githubusercontent.com/10065385/44249387-ed94ae80-a1ef-11e8-8b4d-cad2896ff862.png)

**Comment by ghost** [comment]
Duplicate Bug #192 

@NCC-Therenall

**Comment by ghost** [comment]
I do remember this bug not long after the storage update and was able to replicate with regularly. Currently, I am unable to reproduce this bug.

Going to close this for now. If it does pop back up we can reopen this issue.

**Comment by ghost** [comment]
Reopening. Therenall brought this to my attention that this does still occur.

**Comment by NCC-Therenall** [comment]
This should be fixed in an upcoming patch. When you very high repair (>150) it would cause the XP gain to go negative.
