### ISSUE TITLE
Crahn Lightning Bolt

### ISSUE THREAD

**Issue by ronmcsw** [NCC-Lykos/neocron-classic#304]
i was checking the classic wiki for the next APU Module to get and saw this at TL15 when i chacked both the plaza 1 and pepper park 3 shops this was not for sale in either i commented in discord and Gnisha advised to post as it is either a wrong posting on the wiki or its a bug hope i got this right this time thanks

**Comment by ghost** [comment]
Fixed.  Awaiting patching.

**Comment by ghost** [comment]
Patched.
