### ISSUE TITLE
[B#65] List of Bugs with recent patch.

### ISSUE THREAD

**Issue by Robo-Combyte** [NCC-Lykos/neocron-classic#306]
A host of new bugs have appeared with the recent RPOS patch that makes things difficult and confusing.

- [x] Various windows (GoGuardian, Contents etc) never remains in the same area on screen defined by the user, always reverts to default location.

- [x] GoGuardian and Contents storage is scrambled, trying to select an item selects items above it, even if it's an empty slot.

- [x] GoGuardian icons slightly off center, going upwards

- [x] PvE Sectors such as Plaza Sec-1, Via Sec-1 & 3 get reverted back to Secure sectors upon entering, chat will warn twice of the sector rules, first PvE, then Secure.

- [x] Apartment console is broken, clicking Ground Floor or Ok closes the window and won't reopen, forcing to use the Gene Rep.

- [x] Citycom Missions have practically no missions to select, 99% of them read "text not found".

- [x] On revival from death, "Ghost" armor of previously equipped armor exist in the armor slots, upon removal into inventory, they go away, previously equipped armor still goes into inventory after revival.

- [x] Many NPCs are missing, Copbots, the Creeper guy in Plaza Sec-1 and various other areas, probably more than I've seen so far as well.

- [x] Gene Rep list is overflowing, locations flood out past the bottom of the window.

- [x] After death trying to teleport to anywhere teleports to last visible Gene Rep in the list.
Workaround: Place your desired location at the bottom of the currently visible list.

Found by: @Skansy 
- [x] PPU Manipulations are considered an Electric Shock instead of Psi Manipulation. https://github.com/NCC-Lykos/neocron-classic/issues/306#issuecomment-415953223

Found by: @Amoney1 
- [x] Poison stacks show up as intoxication. https://github.com/NCC-Lykos/neocron-classic/issues/306#issuecomment-415974008

**Comment by Skansy** [comment]
![image](https://user-images.githubusercontent.com/32749567/44616506-74313780-a851-11e8-8847-cf465203a108.png)
Maybe all PPU Spells are listed as Electric Shock

**Comment by hazuk** [comment]
i cant get out of my appartment the elevator button is broken
crosshair is buggin dont remember my rpos color its the grey one
the genrep window is broken...
can you guys please stop destroy the game ? maybe patch bugs first ?????????? before add new  stuff?

**Comment by Amoney1** [comment]
posion stacks show up as intoxication

**Comment by NCC-Lykos** [comment]
Updated the list above to show what has been fixed. Continuing to work through the list. No patch yet.

**Comment by NCC-Lykos** [comment]
Going to consider this list fixed. If it is not, please reference it in a new bug report.

**Comment by NCC-Lykos** [comment]
CityCom Missions are still broken on live server.

**Comment by ghost** [comment]
Closing this as Zodiac fixed the terminal missions a few patches back.
