### ISSUE TITLE
List of Bugs/RPOS Errors

### ISSUE THREAD

**Issue by Robo-Combyte** [NCC-Lykos/neocron-classic#310]
Instead of making multiple reports, I will consolidate them into another list. Will expand as issues are found.

### Bugs:

- [x] Resists are Broken...

- [x] Copbot textures got screwed up after i died in the sewers to a Cankered Plant and then GeneRep to Plaza Sec-1. Goes away after zoning
*Snipped this -Lykos*

### RPOS Errors:
- [x] People List: https://github.com/NCC-Lykos/neocron-classic/issues/308

- [x] Trade menu is misbehaving, text is offset, items go into name plates above (will attempt to get a better image of this)
![image](https://user-images.githubusercontent.com/42428000/46557740-8a9acc00-c8b0-11e8-81a6-c54c56081f15.png)

- [ ] Buy/Sell numbers are stacked on top of one another
![image](https://user-images.githubusercontent.com/42428000/46557816-d188c180-c8b0-11e8-9aec-b879c8b08110.png)

- [ ] Certain status effects have new and old graphics stacked on top of one another 
![image](https://user-images.githubusercontent.com/42428000/46566301-7d4a0580-c8e1-11e8-865c-843cb6f3542c.png)

### Misc:
- [x] Sector Security: https://github.com/NCC-Lykos/neocron-classic/issues/309

**Comment by ghost** [comment]
my  //RPOS Scaling value jumped  after the latest patch [B#66]  to 1.5 and some to 2.0 ... my rpos was huge and looked terrible...  1920*1080
i changed them all to 1.0 in the config and now the rpos is looking fine again ..
no idea if this is a resolution bug or just the wrong value was set by the patch.. so i report it here maybe it will help

**Comment by Robo-Combyte** [comment]
> 
> 
> my //RPOS Scaling value jumped after the latest patch [B#66] to 1.5 and some to 2.0 ... my rpos was huge and looked terrible... 1920*1080
> i changed them all to 1.0 in the config and now the rpos is looking fine again ..
> no idea if this is a resolution bug or just the wrong value was set by the patch.. so i report it here maybe it will help

Yeah, this was just an oversight by the devs, it can easily be fixed.

**Comment by NCC-Lykos** [comment]
Yes I apologize for the RPOS scale, I made a hard oops.

**Comment by NCC-Lykos** [comment]
The Copbot issue, have you had this happen again?

**Comment by Robo-Combyte** [comment]
No, this only happened once, it may happen very rarely, but I thought I'd leave it there anyways

**Comment by NCC-Lykos** [comment]
I think it was like a....random half patched error. Let's check it off for
now. If it comes back we will check into it.

**Comment by hinch** [comment]
![shot0005](https://user-images.githubusercontent.com/2182589/46942160-a0548200-d064-11e8-9417-142480aeb051.png)

couple of bits.

- Team window missing ? icon in top right just black space.
- processor construction time line doesn't go all the way to the end of the box .
- implants scroll bar on left ? should be centered in that left hand column i believe or certainly not dropping behind the effects and implants.
- The X and ? on the top right are there even when the rpos is closed and  the clock text isn't aligned central also green bar going along the top is a different height to the X and ? if you're leaving them.
- Factions box ? and X alignment completely different to all other windows.
- processor top green bar should go all the way along to the ? like the other boxes.



Just for QoL can you make the small map always appear on its always pissed me off that it closes when you quit the client and you have to go into nav ray again to turn it on. Just default it on.

**Comment by Robo-Combyte** [comment]
1. Processor bar doesn't extend all the way because the number of percentage to completion goes in that empty space

2. I don't think I ever remember a "?" button on teams window, don't think it has much to explain itself about

**Comment by hinch** [comment]
1) ok just looks weird
2) it may not have but then the header bar needs to extend all the way to the X otherwise you just end up with an unfinished UI with a black random box in it.

**Comment by rhomm-dev** [comment]
The clickable area to select the apartment code text field is off. It currently is something like this (red area is clickable): 
![ncc_clickable_text_area](https://user-images.githubusercontent.com/34965105/48804864-c4e6ee00-ece3-11e8-987d-00ecd90bdcc3.png)

**Comment by NCC-Therenall** [comment]
So the buy and sell numbers being stacked actually isn't a bug, but it wasn't very well done on my part I guess (I forgot about the text at the top, too.) 

The window wasn't wide enough, even after widening it, to fit the reqs and the buy/sell numbers, and I didn't want to deal with widening it again at the time.

I suppose we could move them to more of the middle level (vertically) so they wouldn't overlap with the reqs when they get too wide?

**Comment by Robo-Combyte** [comment]
I think with some graphical modification you could do that and move them more to the middle, but have the buy and sell text over the numbers respectively should do.

EDIT: Better yet even have them sitting next to the prices

**Comment by ghost** [comment]
Adding to the "Certain status effects have new and old graphics stacked on top of one another" -- I experienced this just now in the Aggie Cellars.

**Comment by hinch** [comment]
also throw this one in here 
UI thing for intoxication vanishes as does the snow but the movement impairment effects remain until you zone.

**Comment by NCC-Therenall** [comment]
Checked off resists, because they should be working now, and we should have some nice improvements on the way this coming patch :)

**Comment by NCC-Lykos** [comment]
Closing this issue, if any remain please test first and then open a new issue.
