### ISSUE TITLE
Feature Request MouseButton2 GoGuardian and other menus

### ISSUE THREAD

**Issue by quadrant2005** [NCC-Lykos/neocron-classic#311]
Feature request i see pressing mousebutton2 opens all menus when at a goguardian pls could you make it so pressing again would close all menus,  i guess this may work well in other places to so the mousebutton two toggles open and closed cheers regards this saves pressing F1 and Esc etc when using other menu systems would be nice to have the option to use mousebutton2 to also close them

**Comment by NCC-Lykos** [comment]
Tab will open and close RPOS.

Right mouse is for right clicking items for more information, to use them and other functions.
