### ISSUE TITLE
Bug Zone change plaza_p1 to plaza_p4

### ISSUE THREAD

**Issue by quadrant2005** [NCC-Lykos/neocron-classic#312]
ive found going from plaza_p4 into plaza_p1 is fine but if you go back the other way not sure if this is always at this time will follow up on this going from plaza_p1 to plaza_p4 will drop you out of the server. If there has been other issues reported like this, that could be when the player is accessing the server database i guess, i have seen this issue with mysql database etc in the past with some mods that we experimented with this method, in the end we moved away from mysql databases and created the GDS Global Database System for all the servers to be able to use the same database if running the same mod. cheers regards [QBS]Quadrant2005

**Comment by ghost** [comment]
I've zoned between Plaza 1 <-> Plaza 4 and back numerous times and have not crashed.

A number of different things can cause the behavior that you're experiencing.  For example, if you loose sync with the server and go to zone, yu'll crash/get kicked back to login.

**Comment by quadrant2005** [comment]
hi there Gnish, its when ever i go to plaza_p4 by going up the ramp by the
admin center on plaza_p1 and using the zone change up there. Ive checked
and i seem to get it every single time. I then rejoin and im then in
plaza_p4 i can go back the opposite way fine, i can reproduce this many
times ? This is the only location that i believe i ever have this happen
which i find stange, cheers regards Richard quadrant2005
