### ISSUE TITLE
If you are ingame and have like the Processor Window open F7 and click on the "?" next to the "X" 

### ISSUE THREAD

**Issue by MigStrobel** [NCC-Lykos/neocron-classic#314]
If you are ingame and have like the Processor Window open F7 and click on the "?" next to the "X" than a Window will pop up that cant be removed and the Window has nothing in it

**Comment by ghost** [comment]
![processorhelpwindow](https://user-images.githubusercontent.com/32779211/46581043-2f72f180-c9f6-11e8-8a6c-7c1d9356cc73.jpeg)

Unable to duplicate this.  All windows that I open and click the '?' icon, the popup window contains text and is closable.
