### ISSUE TITLE
Tangent Epic last mission won't start

### ISSUE THREAD

**Issue by dutchmaestro** [NCC-Lykos/neocron-classic#318]
Dialog with FMS at Tangent HQ seems to work as expected but mission is not started/added to mission log so when you talk to Andressa in Via Rosso Sec-1 she just tells you to go away. I've tried with both mission log empty and after doing a quickjob (kill aggressor caps) to see if it resets but didn't make a difference.

There is no message that tells you why the mission won't start. Also, its not possible to cancel active missions via the cancel mission button which might be related.

**Comment by dutchmaestro** [comment]
I was able to reproduce this with another character.. Means can't get FSM access so no clan key is right?

**Comment by ghost** [comment]
Confirmed this issue.  Investigating.

**Comment by ghost** [comment]
@dutchmaestro In response to the "No FSM access" and no clan keys; Neocron 1 doesn't have Faction Supply Managers (FSMs).  However, once the epic run is completed, yu'll be able to purchase a clan key from the Human Resource Manager.

**Comment by NCC-Lykos** [comment]
Fixed.
