### ISSUE TITLE
pimps in peper 1

### ISSUE THREAD

**Issue by ghost** [NCC-Lykos/neocron-classic#319]
while leveling on pimps in peper 1 i found that this 2 pimps have the same spawn point or they bug inside each other after respawn... here screenshots for proof
![shot0002](https://user-images.githubusercontent.com/32795552/46970460-6c577c00-d0b9-11e8-8be8-53edeab9ba83.png)
![shot0003](https://user-images.githubusercontent.com/32795552/46970461-6c577c00-d0b9-11e8-96b2-a08d75e94b9c.png)

**Comment by ghost** [comment]
The spawn points for these two particular chums have been adjusted slightly to avoid them crashing into each other when attempting to walk back to there spawn points.

**Comment by NCC-Lykos** [comment]
Further redesign of the area will prevent this from happening. Will have it ready for a patch soon.

**Comment by ghost** [comment]
the ability to walk would be nice for them :) at the moment you can get there easy exp and money
