### ISSUE TITLE
Black Lilly 

### ISSUE THREAD

**Issue by ghost** [NCC-Lykos/neocron-classic#320]
she is again stuck in boxes you fixed it 2 times or more... move her to the wall. see screenshot
![shot0004](https://user-images.githubusercontent.com/32795552/47022695-56e85d80-d15e-11e8-8e43-c52f88517460.png)

**Comment by ghost** [comment]
Her placement is correct on my screen.

**Comment by ghost** [comment]
i talked to her for a epic run after the dialog she was stuck. loged off and came back few hours later and she was still inside the boxes.

**Comment by ghost** [comment]
She's still in the correct location here after a week, and the other runners I've seen in-game also see her in the proper location.  I've even let her respawn a few times and respawns properly.  I'll leave this open though and double check her location the next time the server restarts to make sure the server is spawning her in the initial location properly.

**Comment by hinch** [comment]
just logged in to check and she's leaning against the boxes not inside them

**Comment by ghost** [comment]
shes back at her position....
![shot0003](https://user-images.githubusercontent.com/32795552/47646441-36fc6500-db74-11e8-80a2-2dc184451249.png)

killed her and she respawn in boxes...
![shot0000](https://user-images.githubusercontent.com/32795552/47969723-4865d580-e07c-11e8-930a-636e31389dea.png)

**Comment by ghost** [comment]
Sending this over to @NCC-Camarogue to have him rework this model so she can be placed against the wall without her hind leg just hanging in the air.

**Comment by hinch** [comment]
> Sending this over to @NCC-Camarogue to have him rework this model so she can be placed against the wall without her hind leg just hanging in the air.

hind leg? she has 4 now?

**Comment by ghost** [comment]
> hind leg? she has 4 now?

The legs/shoes.  The shoe doesn't line up with her back, so even when she's positioned with her back against the wall, the "shoe" is still inches away from the wall.

**Comment by ghost** [comment]
Some more looking into this.  I've killed Black Lilly a handful of times with various different weapons and every time she has properly spawned.  However, when I killed her, ran into a different zone, and came back to her, her corpse was in a different position than when I left her.  Waited with her out of position corpse to repawn and she respawned out of position.

As referenced in Issue #329, I believe this is starting to point more towards bad positioning data from the server.

**Comment by NCC-Lykos** [comment]
Closed as old issue and non priority
