### ISSUE TITLE
[WORLD]OZ-2 Pillars Do Not Connect with the Ground

### ISSUE THREAD

**Issue by DarkPhoenixNC** [NCC-Lykos/neocron-classic#325]
![world oz-2 pillars](https://user-images.githubusercontent.com/44121743/47529563-2eefad00-d876-11e8-8706-7f01d7555b28.png)

Interestingly enough, I seem to remember this in the original beta as well.

**Comment by NCC-Lykos** [comment]
Fixed in next patch
