### ISSUE TITLE
[MOBS] Flying launchers

### ISSUE THREAD

**Issue by dutchmaestro** [NCC-Lykos/neocron-classic#326]
Launchers at MB go flying, not sure what triggers this behavior.
![shot0002](https://user-images.githubusercontent.com/44158433/47614461-72c5fa80-daa0-11e8-9cd2-9642c9187bee.png)

**Comment by NCC-Lykos** [comment]
Well...I mean...they do have rockets under them....

**Comment by dutchmaestro** [comment]
can't argue with that.. also, its quite a cool party trick.

**Comment by NCC-Atlas** [comment]
I experienced this today. They go flying into the air when damaged, or clip into the ground depending on what plain they were on when damaged. Does only happen very rarely.

**Comment by Wastelandscum** [comment]
I think they _should_ go flying, personally.
