### ISSUE TITLE
[UI] Poison stacks display incorrectly

### ISSUE THREAD

**Issue by dutchmaestro** [NCC-Lykos/neocron-classic#327]
Multiple poison stacks aren't displayed correctly in the UI.

![shot0012](https://user-images.githubusercontent.com/44158433/47614506-2d55fd00-daa1-11e8-9212-4d670492270f.png)

![poison_stacks](https://user-images.githubusercontent.com/44158433/47614509-3941bf00-daa1-11e8-8384-c272df5f51c2.png)

**Comment by ghost** [comment]
![poisonstacks](https://user-images.githubusercontent.com/32779211/47628150-20b5c100-db02-11e8-9898-faaa03ab8c66.jpg)
No issues here.

Have you tried to use the File Check option from the Launcher?

**Comment by ghost** [comment]
few days ago i had the same issue .. i tested it again today and it seems to be fixed ?? O_o
![shot0002](https://user-images.githubusercontent.com/32795552/47646259-a6258980-db73-11e8-8e1e-92e922a005c4.png)

**Comment by dutchmaestro** [comment]
yes, can't reproduce this anymore.
