### ISSUE TITLE
[Missions] Negative SL, Keeps Going Negative

### ISSUE THREAD

**Issue by B3ASTMODE82** [NCC-Lykos/neocron-classic#328]
I was -33 SL did 2 easy FA missions now I am -64 SL B3ASTMODE is the char name

**Comment by B3ASTMODE82** [comment]
Haven’t logged on but any luck on this bug ?

**Comment by B3ASTMODE82** [comment]
The missions worked cause my FA faction went up.

**Comment by ghost** [comment]
> Haven’t logged on but any luck on this bug ?

When any information is able to be provided on this issue it will be provided here.  All of our team work full-time jobs, and have families, not 100% of our time is able to be devoted towards this.

**Comment by B3ASTMODE82** [comment]
Ok no problem

**Comment by NCC-Therenall** [comment]
Got this fixed tonight. This should be fixed next patch, probably tomorrow.

**Comment by ghost** [comment]
Confirmed this is fixed.
