### ISSUE TITLE
Faction sympathy and killing anti-city runners in city sectors

### ISSUE THREAD

**Issue by dutchmaestro** [NCC-Lykos/neocron-classic#332]
This is just 1 example; if you kill a TG runner in a city sector (pepper park 1) then this adds to your soullight and faction symp towards your own faction (being TT). As far as I know this should also add faction symp to the other factions that are enemies of TG e.g. Biotech so this could be an issue because it doesn't work as designed?

It makes sense to me that you are rewarded in sympathy towards all city factions that are enemies of anti city runners sneaking into the city. Currently this only adds sympathy to your own faction but you're doing the others a favor as well really and this would make it easier to switch factions within the city.

**Comment by ghost** [comment]
The current implemention of this is correct. Ran this by @NCC-Lykos to double check.

Twilight Guardian kills CityAdmin Runner, they gain Soul Light and Faction Sympathy for Twilight Guardian only.  You do missions for the other factions to boost your sympathy with them.
