### ISSUE TITLE
Yagers Inn (TG Canyon) - not displayed correctly

### ISSUE THREAD

**Issue by belekamus** [NCC-Lykos/neocron-classic#336]
![shot0000](https://user-images.githubusercontent.com/48834006/54832302-2fbd2b80-4cbc-11e9-8f9e-3ed1d04c0b2a.png)
![shot0001](https://user-images.githubusercontent.com/48834006/54832306-30ee5880-4cbc-11e9-8bdd-8873d476fda8.png)

**Comment by ghost** [comment]
Can you post your PC stats? Processor, Video Card, Drivers, Windows version, etc...

**Comment by belekamus** [comment]
I have a Radeon RX 580, using the 18.12.3 Radeon Software (Adrenalin) on Windows 10 64Bit system. 
CPU is AMD Ryzen 5 2600 and 16GB RAM.

To specify the problem a bit more: for example, when I move the mouse to the left, the "yagers inn" graphic is moving to the right. Same the thing to the other direction.

**Comment by ghost** [comment]
@belekamus What resolution are you running Neocron at? If it's an custom resolution, what happens when you use one of the pre-set resolutions?

**Comment by belekamus** [comment]
Normally I use "window mode" (pre-set, which is 2560x1080 I think, since its nearly full screen, monitor/windows resolution is 2560x1080 too).

I also tried both "2560x1080x32" pre-set resolutions, which are listed double in the launcher GFX options.

I also have this issue at OPs, so its not only TG Canyon Yagers Inn:

![shot0002](https://user-images.githubusercontent.com/48834006/55096559-75159a80-50ba-11e9-814b-c78c62f9c2cc.png)
![shot0003](https://user-images.githubusercontent.com/48834006/55096560-75159a80-50ba-11e9-8ee5-ef6a603d9719.png)

**Comment by NCC-Lykos** [comment]
This is a special one, as the devs can't really reproduce it yet.

**Comment by NCC-Lykos** [comment]
This has been fixed for next patch.
