### ISSUE TITLE
Caves (TG Canyon) cause connection problems

### ISSUE THREAD

**Issue by belekamus** [NCC-Lykos/neocron-classic#337]
After a while (tried some more/different caves) I lose connection, when I lvl in caves in TG Canyon:

![tg cave lost connection](https://user-images.githubusercontent.com/48834006/54832402-5f6c3380-4cbc-11e9-8f8e-66df145e4043.PNG)

**Comment by hinch** [comment]
its not unique to the canyon i think in general the world/network stuff seems to be a tad off i've had loads of disconnections/stuck in sync/client just generally crashing which it never used to before this patch guess the migration of the code is still a little questionable in places.

**Comment by belekamus** [comment]
Ok, just thought its a bit special, since the error message mentioned the canyon map (like shown in the screenshot).

**Comment by NCC-Lykos** [comment]
This is general connection issues with the server after switching to x64. Waiting on our guy to look at it.

**Comment by NCC-Lykos** [comment]
This seems to be fixed.
