### ISSUE TITLE
state effects don't carry across zonelines

### ISSUE THREAD

**Issue by hinch** [NCC-Lykos/neocron-classic#338]
get set on fire by fire mob zone fire gone.

**Comment by NCC-Therenall** [comment]
We might have fixed this, I can't reproduce this locally. I've tried spawning grim chasers by a zone line, then zoning, and it's still there. Heal, zone, still there. Etc.

We should be doing a patch tomorrow, can you see if it still does it after the patch?

**Comment by hinch** [comment]
yep i'll check it once patch comes in

**Comment by NCC-Lykos** [comment]
@hinch Any update on this? Worked for me.

**Comment by hinch** [comment]
> @hinch Any update on this? Worked for me.

@NCC-Lykos  not been able to test sorry it booted me out see: connection issue/server crash bug thing and won't let me log back in.

**Comment by NCC-Lykos** [comment]
> > @hinch Any update on this? Worked for me.
> 
> @NCC-Lykos not been able to test sorry it booted me out see: connection issue/server crash bug thing and won't let me log back in.

We closed that issue as we have not been able to reproduce it. Can you email me lykos@neocron.org and I will look at your chars \ account?

**Comment by hinch** [comment]
right i did manage to get back on late last night for an hour the account seemed to start working again  after 6 hours of not letting me in :(

anyway working now and i've tested state effects carrying across zones and into caves etc too and it all seems good and working (certainly for direct affector states)

However I'm not convinced sanctum spells carry across zones, the animation certainly is as is the buff marker on screen however my heal sanctum seemed to stop ticking + hp after zone, recast it it worked fine after that.

**Comment by NCC-Therenall** [comment]
> right i did manage to get back on late last night for an hour the account seemed to start working again after 6 hours of not letting me in :(

I'm unsure what could have happened with your account. I've looked into it and can't find anything. The processes that handle this are entirely separate from the game server, and the game server does nothing with your account. I looked at your account last night, and couldn't find anything wrong with it. So it's pretty bizarre. Absolutely nothing in the neocron source code as a whole changes your username, bans your account, etc. That is all external.

> anyway working now and i've tested state effects carrying across zones and into caves etc too and it all seems good and working (certainly for direct affector states)

> However I'm not convinced sanctum spells carry across zones, the animation certainly is as is the buff marker on screen however my heal sanctum seemed to stop ticking + hp after zone, recast it it worked fine after that.

Thanks, we'll take a look at the sanctum on our end and see if we can see exactly where it may be failing (display issue, actual effect breakage, etc.)

**Comment by ncc-zodiac** [comment]
Tested and confirmed all state effects transfer across zone lines. including ppu sanctums.
