### ISSUE TITLE
RPOS Citycom Runner Search truncation of every 18th entry

### ISSUE THREAD

**Issue by generalcrazy** [NCC-Lykos/neocron-classic#340]
When search runners under citycom the every 18th runner is missing due to truncation of the list.

Confirmed bug at the following resolutions (aspect ratios)
- 1024x768 (4:3)
- 1600x1024 (25:16)
- 1920x1200 (16:10)
- 2560x1440 (16:9)

Screenshots
- 1024x768 (4:3)
![shot0002](https://user-images.githubusercontent.com/18009311/59639337-f401f880-9128-11e9-929b-afc5e4e2582b.png)
![shot0003](https://user-images.githubusercontent.com/18009311/59639348-f6645280-9128-11e9-9598-21a374522c8c.png)
- 1600x1024 (25:16)
![shot0017](https://user-images.githubusercontent.com/18009311/59639764-23fdcb80-912a-11e9-83f3-bc24ed0b147e.png)
![shot0018](https://user-images.githubusercontent.com/18009311/59640320-af2b9100-912b-11e9-80ae-6e5f55c716f1.png)
- 1920x1200 (16:10)
![shot0034](https://user-images.githubusercontent.com/18009311/59640258-7a1f3e80-912b-11e9-982e-f618c7213462.png)
![shot0035](https://user-images.githubusercontent.com/18009311/59640328-b5ba0880-912b-11e9-9ac3-ad33677c5515.png)
- 2560x1440 (16:9)
![shot0029](https://user-images.githubusercontent.com/18009311/59639785-2b24d980-912a-11e9-8e51-b50136335804.png)
![shot0030](https://user-images.githubusercontent.com/18009311/59640333-bbafe980-912b-11e9-842d-c2e18c6f5a31.png)

**Comment by ghost** [comment]
Fixed. -G
