### ISSUE TITLE
Plaza 1 (new Update)

### ISSUE THREAD

**Issue by Skansy** [NCC-Lykos/neocron-classic#341]
a few miss placing bugs

![20190702223412_1](https://user-images.githubusercontent.com/32749567/60545864-5b6c9a80-9d1c-11e9-8120-99c12d4cdacf.jpg)
![20190702223311_1](https://user-images.githubusercontent.com/32749567/60545865-5b6c9a80-9d1c-11e9-8a06-8ed0f3fe8410.jpg)
![20190702223319_1](https://user-images.githubusercontent.com/32749567/60545866-5b6c9a80-9d1c-11e9-9fca-0694b122ddaa.jpg)
![20190702223325_1](https://user-images.githubusercontent.com/32749567/60545867-5b6c9a80-9d1c-11e9-98e7-eec47c8a31a6.jpg)

**Comment by NCC-Lykos** [comment]
These were because of a patch fubar. All fixed.
