### ISSUE TITLE
Mark Cole / PP3

### ISSUE THREAD

**Issue by ghost** [NCC-Lykos/neocron-classic#343]
when i shoot this mark cole npc with my cs i get a sync and get kicked into Login screen..
![shot0001](https://user-images.githubusercontent.com/32795552/60735799-ec2dbb00-9f54-11e9-8c96-c1048d0deac9.png)

here the message from the Login screen
![shot0000](https://user-images.githubusercontent.com/32795552/60735804-f5b72300-9f54-11e9-803d-04a1454a3859.png)

**Comment by NCC-Lykos** [comment]
Oh, that was you crashing the damn server when I was testing lol

**Comment by ghost** [comment]
yep :) btw the outfitter in plaza1 Crash the Server too

**Comment by NCC-Lykos** [comment]
> yep :) btw the outfitter in plaza1 Crash the Server too

I just used the outfitter and did not have issue.

**Comment by ghost** [comment]
> yep :) btw the outfitter in plaza1 Crash the Server too
> 
> I just used the outfitter and did not have issue.

hmmm okay then never mind... yesterday it kicked me in Login screen with Server down message. not tested after latest patch

**Comment by ghost** [comment]
Per Lykos, this should be fixed now.
