### ISSUE TITLE
smal text in the windows at 3840x2160 resolution

### ISSUE THREAD

**Issue by tuxhomer** [NCC-Lykos/neocron-classic#345]
<img width="1918" alt="nc" src="https://user-images.githubusercontent.com/13179348/60786397-b821e800-a156-11e9-848a-44083b5b0aca.png">
 The Text ist hard to read with the 3840x2160 resolution.
A UI Scale option could help.

**Comment by ghost** [comment]
UI Scaling has already been implemented.
See: https://forum.neocron.org/threads/972-B-65-RPOS-Scaling-amp-Misc-Changes

You can find these options within your `My Games\Neocron Classic\settings.toml` file.
