### ISSUE TITLE
Implants and Armor are sometimes buggy

### ISSUE THREAD

**Issue by tuxhomer** [NCC-Lykos/neocron-classic#348]
the calculate from the implant are sometimes buggy.
![before remove the Chip](https://user-images.githubusercontent.com/13179348/60846989-886bf200-a1e1-11e9-97f9-990cee7682fc.jpg)
let's count (example Dex)
5*4=20
20-5=15
![after remove the Chip](https://user-images.githubusercontent.com/13179348/60847075-c406bc00-a1e1-11e9-942c-60880fd19639.jpg)

**Comment by tuxhomer** [comment]
after removing the special i tried to poke the MC5.
![after remove the special try to poke the mc5](https://user-images.githubusercontent.com/13179348/60847421-eb11bd80-a1e2-11e9-8ad6-90ff227d1b99.jpg)

**Comment by tuxhomer** [comment]
just logged in
![just loged in](https://user-images.githubusercontent.com/13179348/60861860-0baa3980-a21c-11e9-8f04-54efeb38aa31.jpg)
I had the MC5 synap and the Special Forces cpu in my brain. Bonus in INT should be 10 not 30.
After put both chips out.
![after remove the mc5 and rare](https://user-images.githubusercontent.com/13179348/60861967-79eefc00-a21c-11e9-8074-73029fb83e1c.jpg)

**Comment by tuxhomer** [comment]
![all in with trader glove buggy](https://user-images.githubusercontent.com/13179348/60870374-04d9f180-a231-11e9-833d-6f551c862270.jpg)

poke implants work
then i put one imp out and put the trader glove at inv.
Try to reimplant the imp with the trader glove this happen.
![put one out then try to reimplant](https://user-images.githubusercontent.com/13179348/60870550-626e3e00-a231-11e9-9386-c0789876b3a8.jpg)

**Comment by tuxhomer** [comment]
![second last](https://user-images.githubusercontent.com/13179348/60873744-24741880-a237-11e9-907f-d5063e2260c4.jpg)
![second last 1](https://user-images.githubusercontent.com/13179348/60873767-2c33bd00-a237-11e9-81e7-19f5a9c1ea98.jpg)
![last](https://user-images.githubusercontent.com/13179348/60873780-335acb00-a237-11e9-9128-227bfaddd1d4.jpg)

**Comment by NCC-Lykos** [comment]
Fixed.
