### ISSUE TITLE
Connection to Nethost lost after few min

### ISSUE THREAD

**Issue by ghost** [NCC-Lykos/neocron-classic#350]
will nc classic get this update too ? it is very frustrating "Connection to Nethost lost" after a few minutes. ipv6 Problem ?!

PATCH NOTES  NEOCRON EVO 
NCE 2.3.1-10 - Xlenium
 Created on 28.12.2018 17:24:24 by NST
Technical & Client Updates
Proxy re-written: Some router had an issue with the TCP connection, the router closed the connection way to early - NC is now sending more signals so the router will not shutdown the connection;
(related Proxy) : "Connection to Nethost lost" after a few minutes fixed;

**Comment by NCC-Lykos** [comment]
I deno, when they share the fix?  🤣  🤣  🤣  🤣  🤣

**Comment by ghost** [comment]
go ask them :P and get the guys in your Team :)

**Comment by NCC-Lykos** [comment]
This has been fixed for next patch.
