### ISSUE TITLE
Power Armor Animation

### ISSUE THREAD

**Issue by ghost** [NCC-Lykos/neocron-classic#352]
Power Armor still have NC2 Model Animation.

**Comment by NCC-Lykos** [comment]
You need to be clearer with this, what animation? Take a video please. What class? What PA? etc etc.

**Comment by ghost** [comment]
@NCC-Lykos  I mean how the Charakter is Walking , Holding a Spell  , Casting spell only with ONE Hand. I Played  a Tank back in the day and the Tanks In PowerArmor walked/movement not like a NC2 Player Model.
Go Ingame  get a Tank Charakter and Walk ,Cast a spell and stuff like this without  a PA and after this Wear a PA and do the same Things.  You can see the Diffrence Instantly ! My English is too bad for explaining :/ 

A PowerArmor should Only Change the Skin from the Charakter! 

The Tank in PowerArmor Need the same PlayerAnimation like the Tank without PowerArmor(not tested other classes i believe they got the same NC2 movement/casting etc).

Screenshot from  the Old days a Tank in PowerArmor with Heal in Hand at the left !
![nc_25](https://user-images.githubusercontent.com/32795552/61248115-bd80c300-a752-11e9-814a-726ab9692581.jpg)

**Comment by ghost** [comment]
https://github.com/NCC-Lykos/neocron-classic/issues/136

**Comment by ghost** [comment]
Issue #136 is a separate issue and is not related.

**Comment by NCC-Lykos** [comment]
Honestly, it would be a lot of work to roll it back or fix. We do have other things on the plate and it isn't really an awful issue....I wouldn't even call it an issue as much as a preference. I'm going to close this as not an issue, we may revisit it later but for now we're leaving it alone and fixing other bugs.
