### ISSUE TITLE
Brightness scale didn´t work in borderless

### ISSUE THREAD

**Issue by Darkeast** [NCC-Lykos/neocron-classic#353]
Brightness scale at borderless mode (and yes i always press Apply changes)
![shot0016](https://user-images.githubusercontent.com/36099859/61112478-3ac6e200-a48c-11e9-809c-d5dc51f66d6a.png)
![shot0017](https://user-images.githubusercontent.com/36099859/61112568-6fd33480-a48c-11e9-8417-b6873986e3a2.png)
 Blightness scale at 1920x1080
![shot0021](https://user-images.githubusercontent.com/36099859/61112632-96916b00-a48c-11e9-9e95-2a1ae7e28180.png)
![shot0022](https://user-images.githubusercontent.com/36099859/61112655-a741e100-a48c-11e9-85af-8ae96b89dff1.png)

**Comment by ghost** [comment]
IIRC Brightness doesn't work in any mode.

**Comment by Darkeast** [comment]
on 1920x1080 it´s work for me

**Comment by NCC-Lykos** [comment]
Brightness adjustment only works when playing full screen, not borderless or window mode.
