### ISSUE TITLE
Edit Outpost Security = Server Crash??

### ISSUE THREAD

**Issue by ghost** [NCC-Lykos/neocron-classic#354]
Edit Outpost Security crash the Server/Zone. See Screenshot for Error Message.

![shot0000](https://user-images.githubusercontent.com/32795552/61178086-bee0ad00-a5e5-11e9-9df0-99225681c867.png)
![shot0001](https://user-images.githubusercontent.com/32795552/61178087-bee0ad00-a5e5-11e9-8f2c-4a76bd3635bf.png)

**Comment by NCC-Therenall** [comment]
Yeah there was an issue with this. I fixed the crash, as well as fixed another issue with the OP security settings. They should be working next patch, will leave this open until it's tested

**Comment by ghost** [comment]
> Yeah there was an issue with this. I fixed the crash, as well as fixed another issue with the OP security settings. They should be working next patch, will leave this open until it's tested

seems to working :)
