### ISSUE TITLE
Issue with implants and requirenments.

### ISSUE THREAD

**Issue by NCC-Therenall** [NCC-Lykos/neocron-classic#356]
If you take a capped monk @ 45 con, implant a filter heart 2 requiring 43 con, it reduces you down to 40 con. 

It appears as though you can then essentially "toggle" the implant on and off by triggering an update (ie: Clicking the + on a subskill.) It will switch to not being able to use it, removing the implant effects but keeping it implanted, to activating it again because now you can use it, reapplying the effects an restarting the cycle.

**Comment by ncc-zodiac** [comment]
Fixed
