### ISSUE TITLE
I think I broke the server (bug)

### ISSUE THREAD

**Issue by hinch** [NCC-Lykos/neocron-classic#357]
ok it seems that when you flood a zone with too many entities and spam barrels on it it dc's you just to sync and then if you're lucky you can log back in or as now it seems to have either crashed the server or broke the forum/account db sync or something as now its giving me 

"account not found, please check your sp" when i  try to log in.

basically get a zone get a couple of terror raptors a couple of percys and a couple of chasers get them all trapped somewhere (i used cycrow gates) spam barrels and wait for the server to vomit.

**Comment by NCC-Lykos** [comment]
I cannot reproduce this. I spawned 100 terror raptors, raptors, grims, etc. I spammed barrels and nothing happened.

**Comment by ghost** [comment]
@NCC-Lykos he crashed the Server 3-4 times. i was playing and lost my car in the wastelands while Server crash

**Comment by NCC-Therenall** [comment]
Maybe, but for now we can't really reproduce it despite trying. How do you know it was him that specifically crashed it? All sorts of things can crash it, it's not exactly the most stable thing, lol. 

Further I can't think of anything that would alter account names or break that system from this. The process that handles login is an entirely separate process from the one that handles world data. Neither have any affect on each other.

I'll play around with a bit too and keep an eye out, and if it seems to crop up we'll re-open this.
