### ISSUE TITLE
walk into the trees

### ISSUE THREAD

**Issue by ghost** [NCC-Lykos/neocron-classic#36]
- [ ] i can walk into the tree near the cycrow lab entrance.... there alot more in the world in some Boxes i can hide too like the ones at the Canyon Reloading Point Genrep room sreenshots here https://forum.neocron.org/threads/550-Cycrow-Lab-Tree

**Comment by NCC-Camarogue** [comment]
The tree you posted has been dealt with and should be in one of the upcoming patches.

**Comment by NCC-Lykos** [comment]
This is referenced in #10 so closing as duplicate issue.
