### ISSUE TITLE
New forum is busted and support osticket site is "offline" so i can't submit it there

### ISSUE THREAD

**Issue by hinch** [NCC-Lykos/neocron-classic#363]
I take it the new forum isn't hooked to our accounts as the old php one was? because apparently my account doesn't exist any more and I can't create a new account as it just keeps giving me this error.

> We cannot detect if your account was created, please ensure you have cookies enabled.

And yes before you ask cookies are enabled and not blocked.

old login and account still work on the main account website etc can you please just link the forum user db to this db as before save having to make yet more accounts everywhere.

**Comment by NCC-Lykos** [comment]
Can you try the new forums again? You will need to register on the new forums as we did not move accounts. https://boards.neocron.org

We will be enabling SSO at some point, but right now our portal is in need of a rewrite because our maintainer left the project long ago. If you signup with the same email you used on the main site, when we enable SSO it will auto link the account.

**Comment by NCC-Lykos** [comment]
We are aware of the osTicket site being offline. Our mailserver setup is quite unique and osTicket has no support for it. We are currently looking into a different ticketing system that will work with our current mail setup, and that may integrate with the game. We will post an announcement when that is ready to go.

**Comment by hinch** [comment]
for ticketing systems look at supportpal (or change your mail server setup :) perhaps try mailcow)

as for the boards still won't let me reg "We cannot detect if your account was created, please ensure you have cookies enabled." still

**Comment by NCC-Lykos** [comment]
> for ticketing systems look at supportpal (or change your mail server setup :) perhaps try mailcow)
> 
> as for the boards still won't let me reg "We cannot detect if your account was created, please ensure you have cookies enabled." still

You are registering ON the boards correct? Like, signup for a new account? I just did it in a private tab and it worked flawless. 

1. Go to https://boards.neocron.org
2. Click on Sign Up
3. Fill out info
4. Click Create New Account
5. Click link that was emailed to you
6. .....?
7. Profit

As for ticketing, we are not interested in changing the mail server setup. We are using mailgun for routing and forwarding of email. We don't have to maintain an SMTP server then and can cut that cost out (mailgun free....smtp server....nope...) and not worry about blacklists....

osTicket should have mailgun support but they don't, and that is a shame. We are going to try using Zammad and see how that works out. We are also looking at other free alternatives.

Let me know about the boards, thanks!

**Comment by NCC-Lykos** [comment]
> for ticketing systems look at supportpal (or change your mail server setup :) perhaps try mailcow)
> 
> as for the boards still won't let me reg "We cannot detect if your account was created, please ensure you have cookies enabled." still

@hinch What browser and plugins are you using that gets the error? I might have found a connection.

**Comment by hinch** [comment]
@ NCC-Lykos  yes i am registering ON the boards sarcastic fucker :)

chrome, CORS extension, tamper monkey and restlet client (restful webservices tester)

as for the ticketing stuff I use supportpal via aws SES services (also free up to something like 1 million emails a month) and it works just fine for both sending via SES and I have inbound mail boxes that it checks too for accepting email tickets. still probably worth a look for you see if it supports mailgun or if there's a plugin for it (its fully extensible via api so there's a loads of plugins out there for it.)

**Comment by NCC-Lykos** [comment]
> @ NCC-Lykos yes i am registering ON the boards sarcastic fucker :)
> 
> chrome, CORS extension, tamper monkey and restlet client (restful webservices tester)
> 
> as for the ticketing stuff I use supportpal via aws SES services (also free up to something like 1 million emails a month) and it works just fine for both sending via SES and I have inbound mail boxes that it checks too for accepting email tickets. still probably worth a look for you see if it supports mailgun or if there's a plugin for it (its fully extensible via api so there's a loads of plugins out there for it.)

So the two Chrome clients having issues, have no extensions in common honestly.... just that its Chrome... the developers are aware of the issue and blame it on Extensions... You should be able to register in a private browsing window. For shits and giggles, can you register at https://try.discourse.org ?

**Comment by hinch** [comment]
worked fine on try.discourse.org using exactly the same browser and plugins,
so its something specific to your configuration i'd say you've not still got the cookies being assigned to your testing domain and they haven't switched over when you've come to the live domain but its checking the live domain cookie ownership so it can't verify the cookie data. Although why its using cookies during a registration process is worrying in the first place as there should be no need.

**Comment by NCC-Lykos** [comment]
> worked fine on try.discourse.org using exactly the same browser and plugins,
> so its something specific to your configuration i'd say you've not still got the cookies being assigned to your testing domain and they haven't switched over when you've come to the live domain but its checking the live domain cookie ownership so it can't verify the cookie data. Although why its using cookies during a registration process is worrying in the first place as there should be no need.

So, there was never a testing domain. The testing domain was boards.neocron.org, and we went live with that address. There is no setting for cookie domain, and we have boards.neocron.org set properly in the configuration. As for why it is using cookies during registration....that is a question for the developers. There is a thread on this issue here -> https://meta.discourse.org/t/we-cannot-detect-if-your-account-was-created-please-ensure-you-have-cookies-enabled/109626/52

The creators blame plugins and browser extensions....but you and the other person with the issue have no extensions in common. It also works with a Firefox no problem. The issue is Chrome, and their boards for some reason. The plugins we use are the following...

```
          - git clone https://github.com/discourse/discourse-voting.git
          - git clone https://github.com/discourse/discourse-solved.git
          - git clone https://github.com/discourse/discourse-chat-integration.git
          - git clone https://github.com/gdpelican/retort.git
          - git clone https://github.com/singerscreations/discourse-stopforumspam.git
          - git clone https://github.com/discourse/discourse-policy.git
          - git clone https://github.com/Ebsy/discourse-nationalflags.git
          - git clone https://github.com/discourse/discourse-math.git
          - git clone https://github.com/discourse/discourse-spoiler-alert.git
          - git clone https://github.com/discourse/discourse-akismet.git
          - git clone https://github.com/discourse/discourse-canned-replies.git
          - git clone https://github.com/discourse/discourse-signatures
          - git clone https://github.com/sudaraka94/preventing-malicious-linking-plugin.git
          - git clone https://github.com/jannolii/discourse-topic-trade-buttons.git
          - git clone https://github.com/featheredtoast/discourse-pwned-passwords.git
          - git clone https://github.com/angusmcleod/discourse-events.git
          - git clone https://github.com/discourse/Discourse-Tiles-image-gallery.git
```

With the malicious linking disabled. If you happen to find some kind of link between any plugins we use and the issue I'd love to help solve it, however we cannot reproduce it on our end. None of our staff members have run into the issue and all of them registered the same way you all do. We have no special settings for using our `@neocron.org` email addresses with the board to skip any type of activation or auto add to any groups. I manually add our staff to the proper groups.

This is one of those frustrating bugs that the Discourse development team cannot reproduce either.

Can you try again though? We have switched our branch back to Stable. It seems the Discourse container helpfully places you on the bleeding edge tests-passed branch....and we REALLY don't want that for production.

**Comment by hinch** [comment]
Looks to be a CORS problem if i had to guess. looks like the path isn't in the allowed script source so its blocking it being loaded in default chrome.  for some reason though when chrome is in private browsing mode it doesn't do the cors checks any more.

boards.neocron.org/:1 Refused to load the script 'https://boards.neocron.org/cdn-cgi/apps/head/QNWX_8GN-3K7wUr6Qa73LdoD3JI.js' because it violates the following Content Security Policy directive: "script-src 'unsafe-eval' 'report-sample' https://boards.neocron.org/logs/ https://boards.neocron.org/sidekiq/ https://boards.neocron.org/mini-profiler-resources/ https://boards.neocron.org/assets/ https://boards.neocron.org/brotli_asset/ https://boards.neocron.org/extra-locales/ https://boards.neocron.org/highlight-js/ https://boards.neocron.org/javascripts/ https://boards.neocron.org/plugins/ https://boards.neocron.org/theme-javascripts/ https://boards.neocron.org/svg-sprite/ https://www.google-analytics.com/analytics.js". Note that 'script-src-elem' was not explicitly set, so 'script-src' is used as a fallback.

account-created:1 Refused to load the script 'https://boards.neocron.org/cdn-cgi/apps/head/QNWX_8GN-3K7wUr6Qa73LdoD3JI.js' because it violates the following Content Security Policy directive: "script-src 'unsafe-eval' 'report-sample' https://boards.neocron.org/logs/ https://boards.neocron.org/sidekiq/ https://boards.neocron.org/mini-profiler-resources/ https://boards.neocron.org/assets/ https://boards.neocron.org/brotli_asset/ https://boards.neocron.org/extra-locales/ https://boards.neocron.org/highlight-js/ https://boards.neocron.org/javascripts/ https://boards.neocron.org/plugins/ https://boards.neocron.org/theme-javascripts/ https://boards.neocron.org/svg-sprite/ https://www.google-analytics.com/analytics.js". Note that 'script-src-elem' was not explicitly set, so 'script-src' is used as a fallback.

**Comment by NCC-Lykos** [comment]
@hinch Could you try again? We made a setting change...

**Comment by hinch** [comment]
still the same end result although the CORS problem now seems to be fixed (at least i'm not seeing the errors in debug now and its correctly calling the script now.)

did you set the autocomplete=discourse on the username field as per that discussion thread on the discourse forums?

if so i'd try disabling autocomplete on the signup form completely rather than even specifying it but you can only disable it on password fields in chrome it appears.
https://www.chromium.org/developers/design-documents/form-styles-that-chromium-understands

you used to be able to use autofill=false or autofill=off but they've disabled that as of chrome 63

apart from that i've also followed the process through in firefox and really can't see any reason for it not working there and not in chrome.  I'm leaning towards a bug in emberjs (or at least the way the discourse guys are handling forms/logins in the js) but unfortunately buzz word bingo with non-production ready libraries strikes again.

**Comment by NCC-Lykos** [comment]
This should be resolved @hinch
