### ISSUE TITLE
[UI] Drop All Button Click Box

### ISSUE THREAD

**Issue by DarkPhoenixNC** [NCC-Lykos/neocron-classic#364]
The clickbox for the Drop All button does not extend to the end of the visual button.

Pic show the button not lit up and the edge of the clickable area.

![Drop All](https://user-images.githubusercontent.com/44121743/61586045-c8639b00-ab38-11e9-94db-0e181a0010ad.png)
Resolution: 1920x1080

**Comment by NCC-Lykos** [comment]
This has been fixed for next patch.
