### ISSUE TITLE
[UI?] Mob Name Errors

### ISSUE THREAD

**Issue by DarkPhoenixNC** [NCC-Lykos/neocron-classic#365]
Was mobbing in CRP and noticed a few dozen Raptors of various types flying around. The one in the following pic caught my eye. Managed to find 3 others with the same name error. 

![Mob Name](https://user-images.githubusercontent.com/44121743/61586059-18daf880-ab39-11e9-8c19-e372cb99e1fd.png)

**Comment by NCC-Lykos** [comment]
Not really 100% sure what is going on with the name. We spawned raptors for testing and then attempted a zone clear. It failed and the raptors remained. It may be an issue with that? Whenever I have the issue a relog clears it up. This is the part of the netcode sending incomplete packets or packets being lost I suppose.

**Comment by NCC-Therenall** [comment]
I actually doubt it's packet loss. This bug has been around for a while on ours (and I seem to remember it being an issue on the retail game way back at some point too.)

I could see it being memory corruption on the client or server. I'll have to do some debugging and figure out if this is client side or server side. Given a relog fixes it, it almost sounds like a client side issue, or an issue where what the server sends is getting ignored or corrupt on either client/server.

I'll look at this one after I finish what I'm working on currently.

**Comment by NCC-Lykos** [comment]
Unable to recreate, may be fixed. Closing.
