### ISSUE TITLE
[WORLD] G13 Desert - Random Terrain Spike in Road

### ISSUE THREAD

**Issue by DarkPhoenixNC** [NCC-Lykos/neocron-classic#366]
(Do ya'll have terrain editing available?)

This has been around since the beginning. G13 Desert, following the road, at the location pictured, ya'll come across a random spike in the world. Looks like an accident since you can't jump vehicles in this game.

![World Bump](https://user-images.githubusercontent.com/44121743/61586081-69eaec80-ab39-11e9-9f73-b673d7fbe986.png)

**Comment by ghost** [comment]
Yet. Can't jump vehicles in this game, _yet_.  (This is totally a joke)

There are a few of these throughout the game world that need to get fixed.

**Comment by NCC-Lykos** [comment]
Fixed
