### ISSUE TITLE
Recycled Ammo Drag to Weapon Causes Total Loss

### ISSUE THREAD

**Issue by DaSaints** [NCC-Lykos/neocron-classic#368]
- Recycled a batch of ammo using junk.
- Dragged completed ammo from processor window (result) into weapon to reload different elemental ammo.
- Weapon gets reloaded with new ammo but looses recycled stack.

**Comment by NCC-Therenall** [comment]
So two questions:

 - For clarity, when you say it loses the recycled stack: Let's say you recycle ammo and it gives you 30 stacks of whatever in the result, you drag that from the result to the weapon, it loads the weapon, and then disregards the entirety of what's left in that stack of 30?

 - Second: Does this also happen if you first drag the recycled ammo from the processor result to the main inventory first, then load the weapon with it?

If putting the stack in your main inventory first fixes the issue, then I have a better idea where to look and it sounds like it's an issue along the lines of "I don't know where to put this so I'm just going to delete it" or something.

**Comment by DaSaints** [comment]
Correct to your first question.  When I drag the finished "30" ammo count straight into the quick slots, it will reload the weapon but "delete" the remaining stacks.

If I drag them first into the inventory (F2) and then move them into the weapon it will decrement correctly and keep the remaining stack in inventory.

**Comment by NCC-Therenall** [comment]
Thanks, sounds like it's just not defaulting to tossing it back into the inventory for some reason, or there's a bug preventing it from properly doing so, and so the stack just ends up being deleted.

I'll have a look at this once I finish my current project.

**Comment by ncc-zodiac** [comment]
Processor result window can only hold a single item not a stack of items. Additional stacks of ammo created through recycling  now are sent to inventory.
