### ISSUE TITLE
Subway Flips

### ISSUE THREAD

**Issue by ghost** [NCC-Lykos/neocron-classic#37]
- [x] the subway do crazy Flips at stop and if you leave the Subway you be land on the track... sreenshots in forum https://forum.neocron.org/threads/538-Subway

**Comment by NCC-Camarogue** [comment]
Sigh... is this still happening on the beta server? i thought i had fixed this issue.

**Comment by ghost** [comment]
is fixed sorry my fault  close please

**Comment by Skansy** [comment]
yep we tested it now for a while ... no flipping :)

**Comment by ghost** [comment]
I can confirm this has been fixed.  Closing this issue. :)
