### ISSUE TITLE
NC Cannot Character

### ISSUE THREAD

**Issue by Slipstream38** [NCC-Lykos/neocron-classic#370]
Hi, 
On my account Slipstream38, I have a Character named bArter Bart. Since this morning after trying to research a hovertech key I cannot longer log in to this character. All other Characters on the account are working. Symptom started when I researched an item would get to 99-100% then I would get booted from the server with the error I emailed you. I would login then start the research item again did this process maybe 10 times each time getting booted. Then it changed and would allow me on for 5 seconds and give the error sent you the screen capture or just bounce me in 5 seconds with the error. Any assistance would be appreciated.

**Comment by NCC-Lykos** [comment]
What item were you researching?

**Comment by Slipstream38** [comment]
A hover tech key got one bp was trying to make three more. And kept failing with me getting booted off. Yesterday I tried to bp a tl44 assault rifle. After zoning I was able to make a bp

Thank you,
Edited by Gnisha removed personal info
________________________________

**Comment by ghost** [comment]
Dont post personal info here. Everyone in the world can see it.

**Comment by NCC-Lykos** [comment]
@Slipstream38 Please verify if this is still an issue.

**Comment by Slipstream38** [comment]
Hello Lykos,

Yes, the issue is still happening, tried several times this afternoon.



Thank you,
Chris Peck
Phone: 310.442.0050
Chris@NeonFlux.net<mailto:Chris@NeonFlux.net>

**Comment by NCC-Lykos** [comment]
This was a direct account issue, fixed and closing.
