### ISSUE TITLE
Salvage disconnections

### ISSUE THREAD

**Issue by Dreab79** [NCC-Lykos/neocron-classic#372]
When trying to salvage an item that sells for 0 NC (in this case Chitin and Poison Glads) the game will allow you to start the salvage, but just as it hits 100% it will disconnect me, and the salvage process will automatically start again when logging back in, forcing me to stop the salvage before it finishes or I get disconnected again.

This may be more than just 0 NC items. I attempted to salvage "Limbs" and the same thing happened as previously stated.

Tested with the TL 30 and TL 55 salvagers with the same results.

**Comment by Dreab79** [comment]
This may be more than just 0 NC items. I attempted to salvage "Limbs" and the same thing happened as previously stated.

**Comment by NCC-Therenall** [comment]
I believe this may be related to an issue we currently have with tradeskills atm. We're looking into it.

Thanks

**Comment by NCC-Lykos** [comment]
This cannot be recreated at this time, assuming fixed. Closing.
