### ISSUE TITLE
vehicle not despawning 

### ISSUE THREAD

**Issue by joeyppu** [NCC-Lykos/neocron-classic#373]
vehicles do not despawn even after 1 day.

**Comment by ghost** [comment]
What zone was the vehicle last seen in?

**Comment by joeyppu** [comment]
Cycro. Next to the op gr. Also when I looted items and dropped them on the ground they did not disappear even after several hours.

**Comment by NCC-Lykos** [comment]
We cannot recreate this at this time, closing.
