### ISSUE TITLE
Wrong exit location - Abandoned Basement Lvl. 2 Entrance in PP1

### ISSUE THREAD

**Issue by generalcrazy** [NCC-Lykos/neocron-classic#375]
Went you leave Abandoned Basement Lvl. 2 in PP1 you exit at the Sewer Lvl 3 Entrance by the Neocron subway in PP1 instead of back at the Abandoned Basement Lvl. 2 Entrance inside A&W.
![image](https://user-images.githubusercontent.com/18009311/87636556-f14c4b00-c70e-11ea-8cd5-26c5a5a54586.png)
![image](https://user-images.githubusercontent.com/18009311/87636610-075a0b80-c70f-11ea-9abd-b16f67612c8b.png)
![image](https://user-images.githubusercontent.com/18009311/87636683-180a8180-c70f-11ea-922a-023a7d0c1eef.png)

**Comment by NCC-Lykos** [comment]
Fixed for next patch.
