### ISSUE TITLE
Sector map text display issue

### ISSUE THREAD

**Issue by Wastelandscum** [NCC-Lykos/neocron-classic#377]
See below, sector display map displays "No map available" in the wrong location. UI scaling on default settings.

![textdisplayissue](https://user-images.githubusercontent.com/68479899/87863004-35a43a80-c90b-11ea-9950-29a4105e972d.png)

As you can see, the text is printed in the upper left of the RPOS regardless of the sector map location, but disappears when RPOS is closed.

![textdisplayissue1](https://user-images.githubusercontent.com/68479899/87863028-9c295880-c90b-11ea-9d21-46ec896a5b87.png)

Also the floating text disappears when you close the sector map window.

![image](https://user-images.githubusercontent.com/68479899/87863061-ed394c80-c90b-11ea-9fc3-a8ee9f1a0a64.png)

**Comment by ncc-zodiac** [comment]
RPOS

**Comment by ghost** [comment]
Fixed.
-G
