### ISSUE TITLE
H_04 minor error with world

### ISSUE THREAD

**Issue by Wastelandscum** [NCC-Lykos/neocron-classic#378]
This barrel in H_04 thinks it's a chair. Posting as I only mentioned it on discord previously.

![image](https://user-images.githubusercontent.com/68479899/87863114-7c466480-c90c-11ea-9526-c1b353c53e8b.png)

![image](https://user-images.githubusercontent.com/68479899/87863121-8b2d1700-c90c-11ea-9601-5c4a9bd487ad.png)

**Comment by NCC-Lykos** [comment]
No more chair
