### ISSUE TITLE
Minor sewer level 1 world terrain issue

### ISSUE THREAD

**Issue by Wastelandscum** [NCC-Lykos/neocron-classic#379]
In sewer level 1, in Plaza 1 for instance,  you can become stuck here frictionless sliding horizontally back and forth along the 'crack' and can't get out without set reset_postion command.

![image](https://user-images.githubusercontent.com/68479899/87863159-17d7d500-c90d-11ea-8bd4-1f4e2dc318b7.png)

**Comment by NCC-Lykos** [comment]
Unable to reproduce, I was able to crouch and move out of the way. We will add a reset_position point to this map.
