### ISSUE TITLE
ingame name creation 

### ISSUE THREAD

**Issue by ghost** [NCC-Lykos/neocron-classic#38]
- [x] i created a Charakter named hazuk after this i created a char named hasuk the game says name already taken

i created a char named fay after this i created a char named lay the game says again Name already taken

i checked the citycom ingame there are no Charakter exist named hasuk and lay...

**Comment by NCC-Lykos** [comment]
Sooooooooooooo looks like we need to overhaul the name checking system.

The name "Hasuk" has the word "Suk" in it which is on the restricted names list.

Also on this list is Diaper, however with the current system you could name your character "Kill all Jews" and that would pass the initial checks, but we would probably force you to change it ourselves.

**Comment by NCC-Therenall** [comment]
What would we do if neocron started making sense?

**Comment by NCC-Lykos** [comment]
Go back to WoW I assume

**Comment by NCC-Therenall** [comment]
Gotta get them legs boi.

**Comment by NCC-Lykos** [comment]
GET ME SOME ESSENCE, FINNA BUSTDAT1000
