### ISSUE TITLE
floating chair in Cityadmin HQ

### ISSUE THREAD

**Issue by Wastelandscum** [NCC-Lykos/neocron-classic#383]
Is this too much? Should I stop?

Numerous chairs in offices on every floor, besides the first floor, are floating. More than a dozen as I started wandering around to check.
![image](https://user-images.githubusercontent.com/68479899/87866619-e37a0e00-c938-11ea-8ab4-4e2fa6a33593.png)

**Comment by NCC-Lykos** [comment]
Fixed
