### ISSUE TITLE
Venture warp Via Rosso 1 - NPCs are facing wrong direction

### ISSUE THREAD

**Issue by Wastelandscum** [NCC-Lykos/neocron-classic#386]
See below

![image](https://user-images.githubusercontent.com/68479899/87867133-b2044100-c93e-11ea-87a0-ae18e00b1119.png)

**Comment by NCC-Lykos** [comment]
Should have correct rotation -- cannot reproduce.

**Comment by ghost** [comment]
@NCC-Lykos it is easy to reproduce. Talk to them and they faceing the right way... leave the zone and get back there and this guys watching the wall again :)
