### ISSUE TITLE
Diamond Real Estate NPCs facing wrong way and missing doors

### ISSUE THREAD

**Issue by Wastelandscum** [NCC-Lykos/neocron-classic#389]
See below

![image](https://user-images.githubusercontent.com/68479899/87867421-82a30380-c941-11ea-8cf2-f34e15f0a7f8.png)

appears to be missing a door on this entry as well when compared to the rest of the hallway...

![image](https://user-images.githubusercontent.com/68479899/87867434-93537980-c941-11ea-8965-cf12c19281fe.png)

**Comment by NCC-Lykos** [comment]
Fixed rotation of NPCs but did not add a door....will come back to that later during faction HQ refresh.
