### ISSUE TITLE
Heal doesnt heal after Sync

### ISSUE THREAD

**Issue by Skansy** [NCC-Lykos/neocron-classic#39]
When u sync to another sector with Heal on ur Charakter, the heal stack up ur HP but jump back to the amount of health u had while syncing.

Than we tested it with Dots (Devourer) when u Sync with Dots they disappear and it shows, that u get all the dot damage instantly but health jump back.

**Comment by NCC-Lykos** [comment]
This issue is hard to decide on, it has to do with things persisting through syncs etc. which is all changed with the netcode changes coming... I don't know if that will fix the issue or not. I'll have to pull in @NCC-Therenall on this one to decide if its even fixed now or not.

**Comment by NCC-Therenall** [comment]
Somehow I missed this one... 

I want to say this is actually fixed in the new storage, but I'll double check when I can.

**Comment by NCC-Therenall** [comment]
@Skansy can you test this again on live, btw? It seems to be working to me, but just want to make sure.

**Comment by ghost** [comment]
@NCC-Therenall Seems to be okay to me.
