### ISSUE TITLE
Models needing refreshing

### ISSUE THREAD

**Issue by Wastelandscum** [NCC-Lykos/neocron-classic#391]
MB Guards.
![image](https://user-images.githubusercontent.com/68479899/87866423-a745ae00-c936-11ea-9580-1b75413f658f.png)

Male Vendor MB Archer & Wesson Advanced Melee Weapons.
![image](https://user-images.githubusercontent.com/68479899/87866465-e7a52c00-c936-11ea-9d23-1c222b147520.png)

Female Vendor MB Archer & Wesson Armor.
![image](https://user-images.githubusercontent.com/68479899/87866473-03a8cd80-c937-11ea-95a1-99482c966a3c.png)

Basically Archer & Wesson in MB is rogue's gallery of ugly NPCs, these are repeated everywhere so I'll only list them once.
![image](https://user-images.githubusercontent.com/68479899/87866499-6306dd80-c937-11ea-9b26-cb3f488b5739.png)

Fat recruitment officer.
![image](https://user-images.githubusercontent.com/68479899/87866513-8598f680-c937-11ea-80f2-13387a91a787.png)

Creeper in the Booty Bunker.
![image](https://user-images.githubusercontent.com/68479899/87866534-d4df2700-c937-11ea-901c-31c05663fbae.png)

I'd like to ask that when made higher definition, she remain ugly, in high def. I've always called her 'Ugly Helga'.
![image](https://user-images.githubusercontent.com/68479899/87866564-46b77080-c938-11ea-88bb-c0908843e9fe.png)

Plaza 1 Diamond Real Estate Vendor (clublike hands)
![image](https://user-images.githubusercontent.com/68479899/87866738-1375e100-c93a-11ea-8fe1-689b16b7ff79.png)

Protopharm Guard
![image](https://user-images.githubusercontent.com/68479899/87866780-78c9d200-c93a-11ea-934b-f7cc3951fbf4.png)

Can George in Protopharm HQ get some love?
![image](https://user-images.githubusercontent.com/68479899/87866814-dbbb6900-c93a-11ea-803d-9b9296fa7e9a.png)

Yo's fat slobs (basically all of them are the same right?
![image](https://user-images.githubusercontent.com/68479899/87866832-2341f500-c93b-11ea-99ea-3382ee99cece.png)

Homeless guy outside Tangent HQ
![image](https://user-images.githubusercontent.com/68479899/87866892-e0345180-c93b-11ea-8203-980d7f7452e7.png)

Homeless guy Via Rosso 3 Chez Sypher
![image](https://user-images.githubusercontent.com/68479899/87866916-373a2680-c93c-11ea-81d9-0173270dbd1f.png)

Don't forget the monk vendors (Via Rosso 3)
![image](https://user-images.githubusercontent.com/68479899/87866979-11f9e800-c93d-11ea-9ddf-d64ff6402816.png)

Patron's of Gariot's Diner in Plaza 4 are all a bit frumpy.
![image](https://user-images.githubusercontent.com/68479899/87867182-6bfbad00-c93f-11ea-9d45-8f0b033b6424.png)

Homeless girl Pepper Park 1
![image](https://user-images.githubusercontent.com/68479899/87867494-1e347400-c942-11ea-82f1-f5d6300bd80a.png)

This hooker in Pepper Park 2 up the first gravlift to right as you enter from Pepper Park 1... weird glitch when she moves.
![image](https://user-images.githubusercontent.com/68479899/87867545-d5c98600-c942-11ea-92c3-2557de0c8dc9.png)
 
Black Lily in Pepper Park 2
![image](https://user-images.githubusercontent.com/68479899/87867567-06112480-c943-11ea-842f-41d07dfaa941.png)

Figaro outside Crahn HQ in PP3
![image](https://user-images.githubusercontent.com/68479899/87867668-55a42000-c944-11ea-8664-0d0502004bae.png)

Reggie in Pepper Park 3 near Venture warp
![image](https://user-images.githubusercontent.com/68479899/87867738-f7c40800-c944-11ea-9310-c904b4f8b709.png)

Lucky in Black Dragon HQ has no eyes :(
![image](https://user-images.githubusercontent.com/68479899/87867900-4f16a800-c946-11ea-8393-345e2de16eb7.png)

Black Dragon HQ Safehouse Keeper
![image](https://user-images.githubusercontent.com/68479899/87867922-6786c280-c946-11ea-9433-3452233fac01.png)

Leone in Black Dragon HQ
![image](https://user-images.githubusercontent.com/68479899/87867960-a9b00400-c946-11ea-8936-6cfd923d64e5.png)

Female NPC in Pussy Club - maybe also... change that awful dance animation.
![image](https://user-images.githubusercontent.com/68479899/87868006-fdbae880-c946-11ea-8cda-b90490d50fca.png)

Dancing Dave and his "buddy" in Pussy Club
![image](https://user-images.githubusercontent.com/68479899/87868011-0ad7d780-c947-11ea-9a8e-0c1a0a938809.png)

Creepy smiling vendors on bottom floor of Pussy Club
![image](https://user-images.githubusercontent.com/68479899/87868048-4f637300-c947-11ea-9351-b05daa07db97.png)

Jester just inside Pepper Park 1 Tsunami HQ (fake one)
![image](https://user-images.githubusercontent.com/68479899/87868146-1546a100-c948-11ea-9840-5484037736bb.png)

that's a lot. I'll do TG and misc wasteland NPC for quests later.

**Comment by Wastelandscum** [comment]
Twilight Guardian Guard
![image](https://user-images.githubusercontent.com/68479899/87894428-9a3cc380-c9f7-11ea-9ec9-3812cf8de541.png)

Twilight Guardian female NPC near Canyon Apartments 2
![image](https://user-images.githubusercontent.com/68479899/87894495-c9533500-c9f7-11ea-912a-ada46b7c3e48.png)

Twilight Guardian femail NPC at Yager's Inn
![image](https://user-images.githubusercontent.com/68479899/87894574-f9023d00-c9f7-11ea-9a8a-8b51edcd3600.png)

Twilight Guardian male NPC at Yager's Inn
![image](https://user-images.githubusercontent.com/68479899/87894640-26e78180-c9f8-11ea-8ccc-66f4ddb5c639.png)

Donovan at Yager's Inn is a bit twisted
![image](https://user-images.githubusercontent.com/68479899/87894670-44b4e680-c9f8-11ea-99f6-bfdf64bf1bd7.png)

Psi vendors at Canyon Trading Post
![image](https://user-images.githubusercontent.com/68479899/87895134-7bd7c780-c9f9-11ea-9432-d70c01a48ca3.png)

**Comment by NCC-Lykos** [comment]
All of these models have been updated.
