### ISSUE TITLE
Twilight Guardian Canyon vendors bugged

### ISSUE THREAD

**Issue by Wastelandscum** [NCC-Lykos/neocron-classic#392]
All the vendors in the Northeastern most vendor area area are buy all's and sell nothing. 
![image](https://user-images.githubusercontent.com/68479899/87895356-11735700-c9fa-11ea-8f78-4ae24992a035.png)

![image](https://user-images.githubusercontent.com/68479899/87895385-2354fa00-c9fa-11ea-8e26-811217802e73.png)
![image](https://user-images.githubusercontent.com/68479899/87895393-29e37180-c9fa-11ea-8278-7d57846d9713.png)
![image](https://user-images.githubusercontent.com/68479899/87895400-310a7f80-c9fa-11ea-9c7d-bdc916bb53e8.png)

**Comment by Wastelandscum** [comment]
There's no where to buy medkits or stam boosters currently that I can find, as well.

**Comment by NCC-Lykos** [comment]
Removed vendors, they are leftover from FSM
