### ISSUE TITLE
Viarosso Subway 

### ISSUE THREAD

**Issue by ghost** [NCC-Lykos/neocron-classic#397]
you still get stuck when you leave the subway after latest patch [1.1.9] Lots of stability fixes.
![shot0002](https://user-images.githubusercontent.com/32795552/97128122-c759ea00-173b-11eb-8a31-591f47f6e91d.png)
![shot0000](https://user-images.githubusercontent.com/32795552/97128118-c3c66300-173b-11eb-9587-dc629d155826.png)

**Comment by NCC-Lykos** [comment]
Cannot reproduce, seems to be fixed.
