### ISSUE TITLE
Npcs with Chair

### ISSUE THREAD

**Issue by ghost** [NCC-Lykos/neocron-classic#398]
All Npcs in the world with a Chair are buggy after latest patch [1.1.9] Lots of stability fixes. See Screenshots
![shot0002](https://user-images.githubusercontent.com/32795552/97128343-5ff06a00-173c-11eb-818c-dfe34d14de3c.png)
![shot0000](https://user-images.githubusercontent.com/32795552/97128336-58c95c00-173c-11eb-8673-82b900ac1bd6.png)
![shot0001](https://user-images.githubusercontent.com/32795552/97128340-5e26a680-173c-11eb-8123-b16b1cb0e260.png)

**Comment by NCC-Lykos** [comment]
Fixed.
