### ISSUE TITLE
Repair tool causes a server crash

### ISSUE THREAD

**Issue by dutchmaestro** [NCC-Lykos/neocron-classic#401]
I was logged in with Rift (monk), using the trade glove and tl75 tool to repair a holy spirit helmet. The correct amount of repair lube was taken from inv. but when the processing window reached 100% myself and another player were kicked. When I logged back in the repair lube was gone which is strange since it only tool 19 out of 200. It was reproducible after trying again the same thing happened.
![shot0006-1](https://user-images.githubusercontent.com/44158433/97234181-2ec57780-17d8-11eb-833e-94ef746d5039.png)

**Comment by NCC-Lykos** [comment]
Possible fix in game right now......need you to retest.

**Comment by dutchmaestro** [comment]
I cant reproduce it anymore, good job :)
