### ISSUE TITLE
Military Base Sewer Entrance 

### ISSUE THREAD

**Issue by ghost** [NCC-Lykos/neocron-classic#404]
There is a hidden Military Base Sewer Entrance inside the walls... when you enter the militarybase on the left side at the yos trader next to appartments Barracks 2
![shot0000](https://user-images.githubusercontent.com/32795552/98063124-979f9600-1e4f-11eb-865d-1c202fe56328.png)

**Comment by ghost** [comment]
when you leave the hidden sewer you spawn next to a lvl 1 sewer... see screenshot for exit location
![shot0001](https://user-images.githubusercontent.com/32795552/98064024-a38c5780-1e51-11eb-9441-697684940825.png)

**Comment by NCC-Lykos** [comment]
Resolved in future patch
