### ISSUE TITLE
slip dungeon

### ISSUE THREAD

**Issue by Moerdog** [NCC-Lykos/neocron-classic#406]
Hello, I found a slip entrance to a dungeon.
In MB, if you go in from outside, the left Yo Shop room.

**Comment by Moerdog** [comment]
![grafik](https://user-images.githubusercontent.com/73964221/98160430-7c2f9c00-1ede-11eb-868e-47ed89c92305.png)

**Comment by NCC-Lykos** [comment]
Fixed in future patch.
