### ISSUE TITLE
144Hz / 165Hz Monitor

### ISSUE THREAD

**Issue by ghost** [NCC-Lykos/neocron-classic#407]
when i set my monitor to 144Hz / 165Hz the fps limit will raise up to 170 and i get massive fps jumpes from 170-120 big ingame lags.

on 144hz/165hz with FPS LIMIT set to 60 the fps will jump from 58-62 all the time and the lags are like without limit

on 60hz i get constantly 62 fps(nvidia fps limit off)

**Comment by hazuk** [comment]
on 60hz i get constantly 62 fps(nvidia fps limit off)
