### ISSUE TITLE
Borderless & 2560*1440 Mode Login Screen

### ISSUE THREAD

**Issue by ghost** [NCC-Lykos/neocron-classic#408]
In Borderless & 2560*1440 Resolution The login screen is messed up the Viarosse Picture is Zoomed in... I Cant Test how it looks when im ingame because Server is currently Offline. 

![image](https://user-images.githubusercontent.com/32795552/140590210-c4b4a157-3911-4324-b10d-7363a424f3ed.png)

**Comment by NCC-Lykos** [comment]
This has already been fixed for a new patch.
