### ISSUE TITLE
D 09 Crest Uplink YO’s trader sells single item

### ISSUE THREAD

**Issue by nIdzzlll** [NCC-Lykos/neocron-classic#411]
Location: D 09 Crest Uplink
Contact Yo’s Pawn Shop Outpost Equipment
[Tested 2022-09-12]

![D 09 Crest Uplink-map](https://user-images.githubusercontent.com/113188846/190266704-8ce8f7d0-ba03-424d-9d0f-c3e17c8b71b7.jpg)

Issue: Trader only sells a TL30 Hacktool. Trade window is scrollable but only one item is listed.

![D 09 Crest Uplink Trader](https://user-images.githubusercontent.com/113188846/190266732-0b392a65-22c2-49b1-b955-36e89e637282.jpg)

Mitigation: Replace trader “Outpost Equipment” with “Cool Drugstore Stuff” or different Weapon/Ammo related function.

**Comment by ghost** [comment]
This is not a bug, and is intended. Each outpost has an NPC that sells items related to that particular type of outpost. I'll get some more stuff added to this group, but the overall seller is intended.
