### ISSUE TITLE
buggy chair in tsunami hq

### ISSUE THREAD

**Issue by ghost** [NCC-Lykos/neocron-classic#52]
- [ ] there is a chair in the tsunami hq which is inside in the floor
![shot0000](https://user-images.githubusercontent.com/32795552/31910859-2047475c-b83f-11e7-8dbf-51d347f462c1.png)

**Comment by NCC-Lykos** [comment]
I believe it is meant to be this way? As in the NPC threw it or somebody was knocked out of it.

I'll have the guys check the area and see.

**Comment by ghost** [comment]
when it meant to be this way then move it higher... it stucks in the ground at the moment... i think it happend after the floor texture upgrade..

**Comment by ghost** [comment]
Fixed.
