### ISSUE TITLE
neofrag sign pp2

### ISSUE THREAD

**Issue by ghost** [NCC-Lykos/neocron-classic#56]
- [ ] the neofrag signs in pp2 are to large....

![shot0001](https://user-images.githubusercontent.com/32795552/31912299-b483bdca-b843-11e7-921c-42754ca50044.png)
![shot0000](https://user-images.githubusercontent.com/32795552/31912310-ba723054-b843-11e7-9057-2d787382e05a.png)

**Comment by NCC-Lykos** [comment]
That is the point, stand back from it lol

**Comment by ghost** [comment]
the ultimate in virtual deathmatch... i mean this one NOT NEO     FRAG

**Comment by NCC-Lykos** [comment]
Ohhhhhhhhhh crud I'm sorry.

**Comment by ghost** [comment]
:)

**Comment by NCC-Lykos** [comment]
Fixed
