### ISSUE TITLE
no hitbox npc / pp3

### ISSUE THREAD

**Issue by ghost** [NCC-Lykos/neocron-classic#58]
- [ ] there is a npc in pp3 with no hitbox /name
![shot0001](https://user-images.githubusercontent.com/32795552/31912926-d8ca88c4-b845-11e7-9fd1-7643cf695393.png)

**Comment by NCC-Lykos** [comment]
In the future please have your mini map open for these screen shots.

**Comment by ghost** [comment]
okay.. btw this is the back entrance from pussyclub in pp3...

**Comment by ghost** [comment]
Fixed.
