### ISSUE TITLE
Entering new district : POPUP-MESSAGE

### ISSUE THREAD

**Issue by ghost** [NCC-Lykos/neocron-classic#61]
- [ ] is it possible that you remove this entering new district popup-messages from the game ?? it is only disturb and not helpfull
![shot0000](https://user-images.githubusercontent.com/32795552/31915268-1d1bf83e-b84e-11e7-9f8c-ccca974cac7a.png)

**Comment by NCC-Lykos** [comment]
No, these will remain so new  players know what sector they are going into. We will however adjust them at some time so they don't pop up out of nowhere.

Not everybody is a veteran like all of us lol

**Comment by ghost** [comment]
navray ?!?!?!?!

**Comment by NCC-Lykos** [comment]
Navray is only useful if you're using it. We won't be changing this one.
