### ISSUE TITLE
fly toxicbarrels / outzone SUBWAY STATION

### ISSUE THREAD

**Issue by ghost** [NCC-Lykos/neocron-classic#65]
- [x] there a some fly toxic barrels at the outzone subwaystation
![shot0000](https://user-images.githubusercontent.com/32795552/31968171-8b726daa-b910-11e7-80dc-57499b333d29.png)
![shot0001](https://user-images.githubusercontent.com/32795552/31968172-8b90a356-b910-11e7-9e96-2f8e54af8e17.png)

- [x] and barrels  buggin in the floor..

![shot0002](https://user-images.githubusercontent.com/32795552/31968173-8baeb292-b910-11e7-901a-e130f8c957c5.png)
![shot0003](https://user-images.githubusercontent.com/32795552/31968301-02bc7d10-b911-11e7-92fc-049c0b3d4e94.png)

**Comment by NCC-Lykos** [comment]
So this one was introduced by...somebody at some time I guess, as a wall to block players from running down the subway or some crap. I'll correct this with a proper wall.

**Comment by NCC-Lykos** [comment]
Fixed in next patch

**Comment by ghost** [comment]
@NCC-Lykos see #113 last post
