### ISSUE TITLE
trader in outzone 1 sell wrong stuff

### ISSUE THREAD

**Issue by ghost** [NCC-Lykos/neocron-classic#72]
- [ ] in outzone 1 are 2 yos who sell wrong items.. here screenshots

![shot0000](https://user-images.githubusercontent.com/32795552/31972633-e0ac4d0c-b921-11e7-9002-fc36def501b5.png)
![shot0001](https://user-images.githubusercontent.com/32795552/31972625-db9c6bf8-b921-11e7-850e-3265e11b4e63.png)
![shot0002](https://user-images.githubusercontent.com/32795552/31972626-dbb8f34a-b921-11e7-9e7c-b777d2260de8.png)
![shot0003](https://user-images.githubusercontent.com/32795552/31972627-dbd5270e-b921-11e7-83a5-f08582dd1a3a.png)

**Comment by ghost** [comment]
Outzone, Industrial and Wasteland Traders are on my list to go through and inventory. :)

**Comment by ghost** [comment]
dont forget the hq trader :-) i found 2 trader inside the blackdragon secret hq which should sell appas but they sell nothing.... and i think outzone appas not ingame cant find any trader which is sell outzone apps

**Comment by NCC-Lykos** [comment]
BD Sells Apps in Pepper 3, I don't know what traders in the Secret HQ sold apps but we aren't following the old or NST on that venture. 

We have started moving things around and placing them where WE feel they belong or would do good. Keep adventuring to see where vendors are at :)

**Comment by ghost** [comment]
in the bd hq are 2more fence guys like the guy at the pp3 genrep thats why i thought they should sell appas too .

**Comment by ghost** [comment]
Yo's vendors in Outzone SEC-1 have been fixed.
