### ISSUE TITLE
Outzone Starter Appartment

### ISSUE THREAD

**Issue by ghost** [NCC-Lykos/neocron-classic#73]
- [ ] the citycom is in fly mode and the chair make you stuck in the outzone starter appa here screenshots..
![shot0005](https://user-images.githubusercontent.com/32795552/32004638-9342c416-b9a2-11e7-8960-7fc51474935c.png)
![shot0006](https://user-images.githubusercontent.com/32795552/32004640-93700ade-b9a2-11e7-8f39-fdbc24d62031.png)

**Comment by ghost** [comment]
- [ ] when you leave the appartment you will spawn not at the entrance of the appa you where before you spawn next to another elevator ... wrong spawnpoint after sync ??? outzone sec 1 appas

**Comment by ghost** [comment]
#81

**Comment by NCC-Lykos** [comment]
Fixed.
