### ISSUE TITLE
Proto Pharm HQ Logos

### ISSUE THREAD

**Issue by ghost** [NCC-Lykos/neocron-classic#74]
- [ ] the logos in the protopharm hq are to big see screenshots..
 
![shot0000](https://user-images.githubusercontent.com/32795552/32009868-870c65c2-b9b0-11e7-89ec-ccaad59382d2.png)
![shot0001](https://user-images.githubusercontent.com/32795552/32009870-87476c44-b9b0-11e7-8753-17591a8a24b5.png)
![shot0002](https://user-images.githubusercontent.com/32795552/32009871-876713d2-b9b0-11e7-8a4d-b44b893fd9d6.png)
![shot0003](https://user-images.githubusercontent.com/32795552/32009872-87870e4e-b9b0-11e7-87d5-b79fac8088eb.png)
![shot0004](https://user-images.githubusercontent.com/32795552/32009873-87a6232e-b9b0-11e7-8674-b9f9d5c94d47.png)
![shot0005](https://user-images.githubusercontent.com/32795552/32009875-87c75b48-b9b0-11e7-9ce3-160ed73ba755.png)

**Comment by NCC-Lykos** [comment]
Again, these are projecting out of the sign backs. They will be a little bit larger than the sign at times. Closed.
