### ISSUE TITLE
mine facility / h13 [Zone Crash to Apartment]

### ISSUE THREAD

**Issue by ghost** [NCC-Lykos/neocron-classic#89]
- [ ] when you leave the mine facility in h13 back to h13 you get kicked back in login screen and spawn in starter appartment -.-

**Comment by ghost** [comment]
Just to update this report; I can confirm this is still happening with PL#46.

Updated title.

**Comment by NCC-Lykos** [comment]
Mining Facility 3 has nothing of value in it, and is not used in any missions. We are closing it for the time being until we can open a new section.
