### ISSUE TITLE
Box/pp1

### ISSUE THREAD

**Issue by ghost** [NCC-Lykos/neocron-classic#9]
- [x] can i post it like this ? i mean only link to forum ?  @NCC-Lykos ^^
- [ ] https://forum.neocron.org/threads/733-box-pp1

**Comment by NCC-Lykos** [comment]
Yeah I'll accept this

**Comment by ghost** [comment]
ok

**Comment by NCC-Lykos** [comment]
Fixed

**Comment by ghost** [comment]
not fixed...
