### ISSUE TITLE
black dragon epic appartment wall texture bug ?

### ISSUE THREAD

**Issue by ghost** [NCC-Lykos/neocron-classic#91]
- [x] is this a wall texture bug in the black dragon epic appa ??? see screenshots
![shot0000](https://user-images.githubusercontent.com/32795552/32116224-1308b86a-bb4a-11e7-8851-82ec456b9756.png)
![shot0001](https://user-images.githubusercontent.com/32795552/32116225-13263ea8-bb4a-11e7-9c32-888cb498943e.png)
![shot0002](https://user-images.githubusercontent.com/32795552/32116227-1343b0b4-bb4a-11e7-97bb-f5bf10673d83.png)
![shot0003](https://user-images.githubusercontent.com/32795552/32116228-136310a8-bb4a-11e7-8ce2-20f45f2dc526.png)

**Comment by NCC-Atlas** [comment]
Oh, that's odd. I'm going to talk to Camarogue to see if that may be something caused by something he did, then I'll fix it if not. Thanks for noticing, bud.

**Comment by NCC-Camarogue** [comment]
Stupid NC2 textures... i'll fix it

**Comment by NCC-Camarogue** [comment]
done
